---
title: "DANL 200: Classwork 2 - Data Visualization"
date: 2023-09-22
execute: 
  echo: false
  warning: false
  message: false
---
```{r}
#| include: false

library(knitr)
library(rmarkdown)
library(tidyverse)
library(skimr)
```

# Question 1. Data Visualization - Geometric Objects

## Q1a.
Run this code in your head and predict what the output will look like. Then, run the code in R and check your predictions.

```{r}
#| echo: true
#| eval: false

ggplot(data = mpg, 
       mapping = aes(x = displ, y = hwy, 
                     color = drv)) +
  geom_point(alpha = .4) +
  geom_smooth(se = FALSE)

```


<br>

## Q1b.
What does `show.legend = FALSE` do? What happens if you remove it? Why do you think I used it earlier in the lecture?


<br>

## Q1c.
Recreate the R code necessary to generate the following graphs.

### (a)
```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(alpha = .4) +
  geom_smooth(se = FALSE)
```

<br>

### (b)
```{r}

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes(group = drv), se = FALSE) +
  geom_point(alpha = .4)

```

<br>


### (c)
```{r}

ggplot(mpg, aes(x = displ, y = hwy, color = drv)) +
  geom_point(alpha = .4) +
  geom_smooth(se = FALSE)

```

<br>


### (d)
```{r}

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(aes(color = drv), alpha = .4) +
  geom_smooth(se = FALSE)

```

<br>

### (e)
```{r}

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(aes(color = drv), alpha = .4) +
  geom_smooth(aes(linetype = drv), se = FALSE)

```

<br>

### (f)
```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(size = 4, color = "white") +
  geom_point(aes(color = drv), alpha = .4)
```

<br>

