---
title: "ECON 340: Team Project"
author: 
  - Henry Kemblowski
  - <i>Feedback provided by</i> Byeong-Hak Choe
date: 2023-12-03
execute: 
  echo: false
  eval: true
  warning: false
  message: false
  fig-cap-location: margin

---

The proposal presents a compelling and significant research topic with a clear objective about the cost and consequence of the Clean Air Act (CAA) of CO2 from Power Plants. 


# Feedback

- Include a brief summary on the references you have.
  
- Include more specific examples or case studies.

- Provide additional details on the economic model and theoretical analysis approach.

- The objectives/problems you guys set requires an empirical analysis. If you guys do not think you can finish it by the due, it is okay to do instead literature review regarding the objectives/problems.


- Consider summarizing the following reference:
  - Harvard School of Public Health (2022), [The Supreme Court curbed EPA’s power to regulate carbon emissions from power plants. What comes next?](https://www.hsph.harvard.edu/news/features/the-supreme-court-curbed-epas-power-to-regulate-carbon-emissions-from-power-plants-what-comes-next/)
  - Burtraw et. al. (2014), [The Costs and Consequences of Clean Air Act Regulation of CO2 from Power Plants](https://bcdanl.github.io/pdfs/econ-340-henry-ref.pdf)
  - Highlight for Burtraw et. al. (2011), [Greenhouse Gas Regulation under the Clean Air Act: A Guide for Economists](https://www.rff.org/publications/journal-articles/greenhouse-gas-regulation-under-the-clean-air-act-a-guide-for-economists/)
  - Burtraw et. al. (2011), [Greenhouse Gas Regulation under the Clean Air Act: A Guide for Economists](https://media.rff.org/documents/RFF-DP-11-08.pdf)
  - World Resources Institute (2009), [Bottom Line on Regulating Greenhouse Gases Under The Clean Air Act](https://www.wri.org/research/bottom-line-regulating-greenhouse-gases-under-clean-air-act)

  


# Suggested Economic Model

- Consider the four economic agents as well as the Social Planner:
  - Power plant
  - Consumer
  - Government
  - Social Planner
  
## Power plant
- Power plant uses either clean energy or dirty energy to produce electricity ($e$).

- Power plant has a continuum of plants, and she can freely adjust its relative proportion of dirty and clean electricity, $\gamma$ and $1-\gamma$, respectively.

- Power plant's total cost of producing electricity from dirty/clean energies consist of variable costs ( $C_{d}(e)$ and $C_{c}(e)$ ) and fixed costs ( $F_{c}$ and $F_{d}$ ):

$$
\begin{align}
TC_{d} &= C_{d}(\gamma\times e) + F_{d}\\
TC_{c} &= C_{c}((1-\gamma)\times e) + F_{c}
\end{align}
$$

- Taking the electricity price $s$ as given, the power plant maximizes its profit by choosing how much to produce electricity $e$ and the proportion of dirty energy power plant ( $\gamma \in [0,1]$  ):
$$
\begin{align}
\max_{e, \gamma}\;\Pi_{e} &=  s e - TC_{d}(\gamma \times e)  - TC_{c}((1 - \gamma)\times e) \\
 &=  s e - C_{d}(\gamma \times e)  - C_{c}((1 - \gamma)\times e) - F_{c} - F_{d}
\end{align}
$$

## Consumer
- Taking the electricity price $s$ as given, consumer maximizes its utility by choosing a numeraire good $x$ and an electricity consumption $e$:

$$
\begin{align}
\max_{x, e}\;U &= x + v(e)\\
\text{subject to }\; Y &= x + se
\end{align}
$$

The above problem is equivalent to:
$$
\begin{align}
\max_{e}\;U &= Y - se + v(e)\\
\end{align}
$$

## Electricity Market

In the electricity market, the electricity price $s$ is such that the supply and the demand for electricity are met:

$$
v'(e) = \gamma C_{d}'(\gamma \times e) + (1 - \gamma) C_{c}'((1-\gamma)\times e)
$$


## Social planner
- Social planner maximizes social welfare, which takes into account the damage caused by greenhouse gas emissions from dirty power plant, as a function of the amount of electricity produced by dirty power plant

$$
\begin{align}
\max_{e,\gamma}\;SW &= \Pi_{e} + U - D\\
&= Y - F_{c} - F_{d} \\
&\quad+ v(e) - \, C_{d}(\gamma\times e)  - \, C_{c}((1 - \gamma)\times e)  - D(\gamma\times e),
\end{align}
$$
where the damage $D(\gamma\times e)$ increases with $\gamma \times e$ at an increasing rate.


## Government
- Government can consider various policies:
  - Setting emission standards to dirty power plants under the CAA
  - Tax dirty power plants
  - Subsidy clean power plants 


## Modeling ideas
- For simplicity, here I abstract away from firm's productions and emissions. Instead, I focus on only power plant and consumer.
- If needed, you guys can always modify the model.





