---
title: "ECON 340: Classwork 1"
date: 2023-09-06
---

# Question 1. Social Welfare and Landfill Regulation
Recently, the U.S.  Environmental Protection Agency issued regulations covering the design and construction of landfills for municipal solid waste.  Landfills can represent a threat to environmental health if toxic chemicals leach from the waste into surrounding ground or surface waters.
<br>

The regulations require certain design, construction and maintenance standards extending beyond the post-closure period, including, in most cases, installation of impermeable liners and covers and groundwater monitoring.  The purpose of the regulations was to ensure safe containment of solid waste and to prevent future generations from having to bear clean-up costs from poorly-disposed waste.
<br>

Even with the new regulations, just under 10% of landfills will still pose what the EPA considers to be a "moderate" health risk for individuals who depend on contaminated groundwater:  a greater than 1 in 1,000,000 increase in the risk of contracting cancer. However, because so few people actually depend on ground water within leaching distance of a landfill, the new regulations were predicted to reduce cancer by only 2 or 3 cases over the next 300 years.  Potential benefits of the regulation not quantified by the EPA include:  increased ease of siting landfills, reduced damage to surface water, fairness to future generations and an overall reduction in waste generation and related "upstream" pollution encouraged by higher disposal costs.
<br>

In aggregate, the regulations are expensive:  about $5.8 billion, or around $2 billion per cancer case reduced.  On a per household basis, this works out to an annual cost of $4.10 in increased garbage bills over the twenty-year life of a landfill.
<br>


## Q1a.	
Using the concept of social welfare represented respectively by equations (1) and (3), 

$$
\begin{align}
SW &= U_{1}\left(\, X_{1},\, P_{1} \,\right) \,+\, U_{2}\left(\, X_{2},\, P_{2} \,\right) \,+\, \cdots\quad &(1)\\
SW &= U_{1}\left(\, X_{1},\, w\times P_{1} \,\right) \,+\, U_{2}\left(\, X_{2},\, P_{2} \,\right) \,+\, \cdots\quad &(3)
\end{align}
$$
explain why the EPA's landfill regulation is (a) too strict and (b) not strict enough.


<br><br>

# Question 2. More on Landfills
Suppose that 100 people live around a hazardous waste dump. If the people continue to live there for 20 years, one of them will likely contract a painful, non-fatal cancer, that will lead to $1 million in health care costs, foregone wages, and pain and suffering.  Assume this is all the damage this waste will ever do (the waste loses its toxicity after 20 years). 
<br>

The Environmental Protection Agency has three choices:

- i. Do nothing.
- ii. Clean up at a cost of $4 million
- iii. Relocate the families at a cost to taxpayers of $1 million; fence off the property for 20 years.

<br>

## Q2a.  
Rank the solutions in terms of efficiency. Explain your reasoning.
<br>

## Q2b. 
Rank the solutions in terms of safety. Explain your reasoning. 

