---
title: "ECON 340: Homework Assignment 1"
date: 2023-09-12
execute: 
  echo: false
---

# Question 1. Negative Externalities I
Consider a society with just two consumers. Consumer 1 can get positive utility from a positive amount of some activity $h$ that she chooses the level of, but consumer 2 gets negative utility from that activity. We can think of $h$ as some non-market good, for example, "hours" of loud music played by consumer 1, disturbing consumer 2's peace and quiet. Consumer 1 therefore imposes a negative externality on consumer 2. Assume there is no other cost associated with the activity.

Assume that both consumers gain utilities from consuming a numeraire good $x$, whose price is 1, but may have different incomes $Y_{1}$ and $Y_{2}$.

- Consumer 1's utility is $U_{1} = x_{1} + h(4-h)$.
- Consumer 2's utility is $U_{2} = x_{2} - h^{2}$.


<br>

## Q1a.
- Under the *efficiency standard*, what is the socially optimal level of $h^{o}$?

- Plot graphs in $(h, \$)$ space, both total and average/marginal, to illustrate the solution.


<br>

## Q1b.
- Derive the market level $h^{*}$ of the activity that results if choosing it is left up to consumer 1, and show that this level differs from $h^{o}$. 

- Add $h^{*}$ to your graphs.

<br>

## Q1c.
Suppose now that the government intervenes in the situation by imposing a tax on $h$. 


- Here is what happens with the tax revenue:
  - Government forces consumer 1 to pay a per-unit tax $t$ on $h$, and to distribute the tax revenue $th$ in some "lump-sum" fashion across both consumers, giving $L_{1}$ to consumer 1 and $L_{2}$ to consumer 2.


- Derive the optimal level of the tax---the level that will induce consumer 1 to choose $h^{o}$ rather than $h^{*}$. 
  - Assume that the government anticipates consumer 1's response to the tax.


- Modify both your graphs from question Q1b to show the effects of the tax.

<br>

## Q1d.
Same question as Q1c, but now the government introduces a per-unit subsidy $s$ paid to consumer 1 for every unit by which she reduces $h$ below some level, for example, her optimal level $h^{*}$ without government intervention.


- Here is how the government prepares the budget for the total amount of subsidy:
  -  Government forces consumers 1 and 2 to pay some amount of "lump-sum" taxes, $L_{1}$ paid by consumer 1 and $L_{2}$ paid by consumer 2, so that the subsidy can be given to consumer 1.


- Derive the optimal level of the per-unit subsidy $s^{o}$---the level that will induce consumer 1 to choose $h^{o}$ rather than $h^{*}$. 
  - Assume that the government anticipates consumer 1's response to the per-unit subsidy $s$.


<br><br><br>

# Question 2. The Tragedy of the Commons

The idea of **the Tragedy of the Commons** was popularized in the late 1960s by Garrett Hardin. He poses the problem facing a herder whose cattle forage on common land. Introducing one more cow onto the common grazing land would lead to a large private gain for this herder in the form of the milk produced by an additional cow. It would also lead to a small private loss to this herder, in that the degraded resource would provide less robust forage for her or his or her existing cows. Of course, the social cost would be much larger, given that most of the loss from the degraded rangeland is externalized and borne by other herders. But if the herder seeks to maximize his or her or her personal gain,

> *The only sensible course for him to pursue is to add another cow to his or her herd. And another, and another… Therein is the tragedy. Each man is locked in to a system that compels him to increase his or her herd without limit—in a world that is limited. Ruin is the destination toward which all men rush, each pursuing his or her own best interest in a society that believes in the freedom of the commons.*


Suppose that it costs $a \in (0, 5)$ for the individual herder to buy a cow. A profit of the individual herder depends only on the value of the milk his or her cows produce and the cost of buying cows. How much milk the cow produces depend on how many other cows are grazed on the common land. Let $f(c) = c(5-c)$ be the value of the milk produced if there are $c$ cows grazed on the common. The value of the milk per cow is just the average product, $AP = \frac{f(c)}{c} = 5- c$.


<br>

## Q2a.
Suppose there is only one herder in the village with the common. The only one herder can freely choose any number of cows.

  - How many cows will be grazed on the common?

<br>


## Q2b.
Suppose there is a sufficient number of herders in the village with the common, so that each individual herder will have a number of cows that is negligible relative to the total number of cows grazed on the common.

  - What is the total number of cows if the individual herder chooses how many of his or her cows to be grazed on the common?

<br>


## Q2c.
Draw the curves for

  - Average product of a cow;
  - Marginal product of a cow;
  - Marginal cost of a cow.
  
Explain the tragedy of the commons using the graphs.

<br>


