---
title: "ECON 340: Classwork 9 - Pigouvian Tax in a General Form"
date: 2023-11-08
execute: 
  echo: false
  eval: true
  warning: false
  message: false
---



<br><br><br>


## Social Planner

The social welfare function is the sum of the consumer's utility ( $U$ ), the firm's profit ( $\Pi$ ), and the damage from the pollution emission ( $D$ ). The Social Planner maximizes the social welfare by choosing the quantity of a good $q$:
$$
\begin{align}
\max_{q}\; SW &= U + \Pi - D\\
&= \underbrace{Y - pq + u(q)}_{U} + \underbrace{pq - c(q)}_{\Pi} - \underbrace{d(e(q))}_{D}\\
&= Y + u(q) - c(q) - d(e(q))\\
\end{align}
$$

### FOC

$$
\begin{align}
\frac{dSW}{dq} = u'(q) - c'(q) - d'(e(q))e(q) = 0
\end{align}
$$


## Consumer
Given the price of a good $p$ and the lumpsum transfer $L$, the representative consumer solves:
$$
\begin{align}
\max_{q}\; U = Y + L - pq + u(q) 
\end{align}
$$


### FOC
$$
\begin{align}
\frac{dU}{dq} = -p + u'(q) = 0
\end{align}
$$


## Firm
Given the price of a good $p$ and the per-unit tax $t$, the representative firm solves:
$$
\begin{align}
\max_{q}\; \Pi = pq - c(q) - tq
\end{align}
$$


### FOC
$$
\begin{align}
\frac{d\Pi}{dq} = p - c'(q) - t = 0
\end{align}
$$

## Market
In the market for good $q$, the equilibrium price is set such that it balances the quantity supplied with the quantity demanded.
$$
\begin{align}
u'(q) = c'(q) + t
\end{align}
$$



## Government
Given the consumer's budget constraint ($Y = x + pq$), the consumer's and the firm's behavior in the market, and the government budget constraint ($L = tq$), the government solves:
$$
\begin{align}
\max_{q, t, L}\; SW &= U + \Pi - D\\
&= \underbrace{Y + L - pq + u(q)}_{U} + \underbrace{pq - c(q) - tq}_{\Pi} - \underbrace{d(e(q))}_{D}\\
&= Y + L + u(q) - c(q) - tq - d(e(q))\\
\;\\
\text{subject to}\quad  L &= tq\\
u'(q) &= c'(q) + t
\end{align}
$$

The above is equivalnet to:
$$
\begin{align}
\max_{q, t}\; SW &= U + \Pi - D\\
&= Y + u(q) - c(q) - d(e(q))\\
\;\\
\text{subject to}\quad  u'(q) &= c'(q) + t
\end{align}
$$
The Lagrangian for the above is:

$$
\begin{align}
\max_{q, t,\lambda}\; \mathcal{L} = Y + u(q) - c(q) - d(e(q)) + \lambda(\,u'(q) - c'(q)- t \,)
\end{align}
$$


### FOC
$$
\begin{align}
\frac{d\mathcal{L}}{dq} &= u'(q) - c'(q) - d'(e(q))e'(q) + \lambda(\,u''(q) - c''(q)\,) = 0\\
\frac{d\mathcal{L}}{dt} &= -\lambda = 0\\
\frac{d\mathcal{L}}{d\lambda} &= u'(q) - c'(q)- t = 0
\end{align}
$$

FOCs for the government problem simplify to:
$$
\begin{align}
u'(q) - c'(q) - d'(e(q))e'(q) &= 0\\
u'(q) - c'(q)- t &= 0
\end{align}
$$

Therefore, we can show that the pigouvian tax is set to be the marginal damage of pollution emission.
$$
\begin{align}
t = d'(e(q))e'(q)
\end{align}
$$

