---
title: "ECON 340: Homework Assignment 4"
date: 2023-11-09
execute: 
  echo: false
---

# Question 1. Controlling Air Toxics

One of the Clean Air Act Amendments passed by the U.S. government in 1990 was designed to control the emission of hazardous air pollutants. The EPA released a publication that year which estimated that at 149 industrial facilities nation-wide, cancer risks to the most exposed local residents from air-borne toxics were greater than 1 in 10 thousand; at 45 plants risks were greater than 1 in 1 thousand.
	
The new air toxics law required firms to impose control technology that, it was hoped, would reduce risks to below the 1 in 10 thousand level. After the control technologies are installed, a follow-up risk analysis will be conducted to see if further control is necessary to further reduce any unsafe exposure. While the legislation does not require risk reduction to the 1 in 1 million level, that remains the long run target.

## Q1a.
- Clearly, air toxics control is justified on safety grounds. Suppose that total benefits of the legislation just matched total costs, at $5 billion annually. 
- Would air toxics control be justified on efficiency grounds?
<br>

**Answer**:

No. If total benefits equal total costs, net benefits are zero, and pollution control is (generally) too strict from an efficiency perspective.  Efficiency occurs where marginal costs and benefits are equal.


<br>

## Q1b.
- Some economist has in fact criticized the legislation from an efficiency perspective. - He puts estimated total costs at $6 to $10 billion per year, with total benefits at $0 to $ 4 billion per year. The air toxics legislation attacks some fairly significant risks. 
- How can the estimated benefits be so low (as low as zero)?

<br>

**Answer**:

Although the risks from exposure to airborne toxics are significant, as with landfills they are fairly localized.  Thus, not that many folks are actually exposed.  (As we noted in the chapter, those who are exposed are more likely to be poor or working class, and/or members of racial minorities.) Some economist argues that 500 reduced cancer deaths per year is a "generous" estimate of the impact of the policy; indeed, he suggests it may be as low as 0.  Five hundred fewer cancer deaths registers in the efficiency framework as monetary benefits of from $1 to $5 billion. 


<br>


## Q1c.
- Suppose the air toxics regulations raised household expenditures on gasoline (due to extra controls on oil refineries) by an average of $20 per year. 
- If millionaire Mary and janitor Jane each paid the extra $20, in what sense is the impact of the legislation regressive? 

<br>

**Answer**:

Regressive policies occur when poor folks pay a higher percentage of their income than do rich folks. Any regulation which costs all people the same dollar amount will thus be regressive. 


<br>


<br><br><br>




# Question 2. Dynamic, Efficiency, Equity and Sustainability

Suppose SUNY is deciding how to dispose of some hazardous waste. She can contain it safely, at a cost of $175, or bury it in the local landfill.  If she chooses the second option, in ten years' time the stuff will have seeped out enough to permanently ruin the vineyard of Geneseo, who lives next door to the landfill. The vineyard has a value to him in ten years of $450 (i.e., he'd sell it then for $450.) This is the only damage the hazardous waste will ever do. Assume there is no inflation.

## Q2a.

- What is the present value of $450 in ten years at a discount rate of 10%?

<br>

**Answer**:
$$
PDV=\frac{450}{1.1^{10}} = 173.49
$$

<br>

## Q2b.

- In the absence of regulation, SUNY is likely to bury the stuff and save $175. 
  - If the interest rate is 10%, is it *efficient* for SUNY to bury her waste in the landfill? 
  - To answer this, discuss how Geneseo could maximize his utility if he had the legal right to prevent the dumping (and was not an ardent environmentalist). 
  - What does this say about the relative size of the total net monetary benefits under the two alternatives?
  - How do total net benefits relate to efficiency?

<br>

**Answer**:

Burial is efficient, since if SUNY banked $173.49, in 10 years time she would have enough to compensate Bacchus for his ruined vineyard. Since she would save $1.51 today, everyone would be better off and no one worse off. If Bacchus could prohibit the dumping, he would nevertheless agree to it, provided SUNY paid him a little more than $173.49 today---thus he would come out ahead too. Note however, that even if Bacchus is not compensated at all for the damage, dumping is still efficient. Efficiency always maximizes total net measurable monetary benefits, that is, the size of the economic pie. When the pie is enlarged, its always possible for everyone to get a bigger slice.



<br>

## Q2c.

- Is burying the waste equitable? Why or why not? Could the use of an environmental bond satisfy a fairness problem if it exists?

<br>

**Answer**:

If Bacchus is not compensated, dumping would be unfair by most people's standards. If SUNY were forced to post an environmental bond of $173.49, than Bacchus would be compensated for damages when they occurred, leading to an outcome that is both efficient and fair.

<br>

## Q2d.
 
- Discuss burying the waste through the lenses of weak and strong sustainability.

<br>

**Answer**:

Strong sustainability proponents tend to argue that natural capital is not easily replaced; the action would thus only weakly sustainable if the natural capital that is destroyed-- a high-quality vineyard-- is in fact replaced by created capital. In this case, for example, the created capital might be biotechnology grapes capable of growing on previously underutilized soil. 

<br>

<br><br><br>

<!-- # Question 3. Two-period Model of Natural Resource Extraction -->

<!-- Consider the economy with two periods---today ( $t=0$ ) and tomorrow ( $t=1$ ). The economy ends after tomorrow. In the economy, there is one single representative consumer that lives only one period. The economy is endowed with 20 units of resources to extract, and the Social Planner of this economy allocates this resources over the two periods: -->

<!-- $$ -->
<!-- \begin{align} -->
<!-- 20 = q_{0} + q_{1}.\tag{RC} -->
<!-- \end{align} -->
<!-- $$ -->

<!-- Let the total cost of extraction be equal to: -->

<!-- $$ -->
<!-- \begin{align} -->
<!-- C(q_{t}) = 2q_{t}. -->
<!-- \end{align} -->
<!-- $$ -->

<!-- Let the total benefit of extraction in each period be equal to: -->

<!-- $$ -->
<!-- \begin{align} -->
<!-- B(q_{t}) = 8q_{t} - \frac{1}{5}q_{t}^{2}. -->
<!-- \end{align} -->
<!-- $$ -->

<!-- So, the total net benefit of extraction in each period is -->

<!-- $$ -->
<!-- \begin{align} -->
<!-- NB(q_{t}) = 6q_{t} - \frac{1}{5}q_{t}^{2}. -->
<!-- \end{align} -->
<!-- $$ -->

<!-- The Social Planner wants to maximize the present value of net benefits over two periods: -->

<!-- $$ -->
<!-- \begin{align} -->
<!-- \max_{q_{0}, q_{1}}\;SW &= 6q_{0} - \frac{1}{5}q_{0}^{2} + \frac{1}{1 + r} \left(6q_{1} - \frac{1}{5}q_{1}^{2}\right) \tag{Dynamic-SP}\\ -->
<!-- \text{subject to}\qquad 20 &= q_{0} + q_{1} \tag{RC} -->
<!-- \end{align} -->
<!-- $$ -->
<!-- where $r > 0$ is the discount rate. -->



<!-- <br> -->

<!-- ## Q3a. -->
<!-- - Use the Lagrangian method to solve the Social Planner's problem (Dynamic-SP). -->

<!-- <br> -->

<!-- ## Q3b.  -->
<!-- - How does the resource extraction in $q_{0}$ varies with $r$? -->
<!-- <br> -->

<!-- ## Q3c.  -->
<!-- - Calculate the present value of the marginal net benefit of extraction in each period in the equilibrium. -->
<!--   - $MB(q_{0}^{*}) - MC(q_{0}^{*})$ -->
<!--   - $\frac{MB(q_{1}^{*}) - MC(q_{1}^{*})}{1 + r}$ -->

<!-- <br> -->

<!-- ## Q3d. -->
<!-- - Compare the present value of the marginal net benefit of extraction in Q3c with the Lagrangian multiplier $\lambda^{*}$ in the equilibrium in Q3a.  -->
<!-- - Explain the result economically and intuitively. -->

