---
title: "ECON 340: Classwork 6 - Mockup Questions"
date: 2023-10-04
---

# Question 1.

## Q1a 
- Redo Q1a-Q1d in Homework Assignment 1 under the safety standard with the constant weight $\omega > 0$.
  - That is, the Social Planner uses the following social welfare function, $SW$:

$$
SW = U_{1}(x_{1},\, h) + U_{2}(x_{2},\, \omega \times h).
$$

<br>

## Q1b
- Suppose that, instead of a tax or a subsidy, the government introduces a marketable-permit scheme. 
  - It gives consumer 2 a bunch of pieces of paper called "permits," each of which states that the holder of the permit has the legal right to "produce" one unit of $h$. 
  - It then allows consumer 2 to sell those permits to consumer 1 at some uniform price $p_{h}$. 


- Assume that each consumer takes the price $p_{h}$ as given. 
  - You can think of each consumer as "representing" a large number of consumers of the same type.


- Show that the scheme will **NOT** achieve the socially optimal outcome under the safety standard.


- What government policy can make the permit scheme achieve the socially optimal outcome $h$ under the safety standard?

<br><br><br>


# Question 2

Groucho and Harpo work together in the same office. Groucho smokes; Harpo hates smoke. Groucho currently smokes 12 cigars per day. He faces marginal costs of reducing smoking (withdrawal pains) equal to $\$x$, where $x$ is the number of cigars reduced. In other words, the cost of giving up the first cigar is $1, the second, $2, and so forth. Harpo receives marginal benefits (reduced discomfort and risk of cancer) equal to $\$(12 − x)$ from Groucho for reducing the number of cigars smoked.

It is possible to rent a clean-air machine that reduces smoke in the air by 50 percent for $\$10$ per day. It is also possible to relocate Groucho in a different office, so Harpo would not have to breathe any smoke at all for $\$40$ per day.


## Q2a.

- Draw a diagram showing the marginal costs and marginal benefits of pollution reduction, with the number of cigars reduced on the horizontal axis. 

- Use this diagram to determine the efficient number of cigars reduced if machine rental or relocation is not allowed.

<br>

## Q2b.

- Suppose that the clean-air machine is installed. What is the efficient number of cigars reduced now? [Hint: The marginal benefits of reduction fall to $\$(6 − \frac{x}{2})$.]

<br>

## Q2c.

- Recall that Groucho begins by smoking 12 cigars a day. Is it more efficient to rent the machine or relocate Groucho to another room?

<br>

## Q2d.

- This problem has no transaction costs or free riding. The Coase theorem says that, in this kind of simple example, the efficient outcome should be achieved through negotiation even if Harpo has the power to banish Groucho to another office at Groucho’s expense. Explain why.

<br><br><br>

# Question 3


## Q3a.
<p>The <span style="border-bottom: 1px solid black; padding-left: 100px;"></span> standard says social welfare does not rise if increases in consumption today, on balance, reduce the well-being of future generations below the level enjoyed today.</p>

## Q3b
<p> Open access to common property results in resource use that is inefficient, unsustainable, or both?  <span style="border-bottom: 1px solid black; padding-left: 100px;"></span>   </p>


## Q3c
<p>   A <span style="border-bottom: 1px solid black; padding-left: 100px;"></span>  policy is one that actually makes all parties better off. </p>


## Q3d
At an efficient level of environmental protection

a. The marginal benefits of reducing pollution exceed the marginal
 costs by a large margin.
b. The difference between the total benefits and total costs of
 pollution reduction are maximized.
c. The net benefits of pollution reduction are zero.
d. No one suffers from exposure to pollution.
e. Social welfare is maximized.
