---
title: "ECON 340: Team Project"
author: 
  - Sarah Ginnane
  - Jack Katz
  - <i>Feedback provided by</i> Byeong-Hak Choe
date: 2023-12-03
execute: 
  echo: false
  eval: true
  warning: false
  message: false
---

PFAS water regulation might be one of the most recent water regulations in the US, which makes the topic more significant and interesting.


# Feedback

- Include more specific examples or case studies.

- Provide additional details on the economic model and theoretical analysis approach.

- If you are interested in details about the health effects of PFAS, check out the following:
  - Agency for Toxic Substances and Disease Registry, *Per- and Polyfluoroalkyl Substances (PFAS) and Your Health*, (2023) [*[Link]*](https://www.atsdr.cdc.gov/pfas/health-effects.html)
  

- The following seems a good summary on PFAS:
  - American Association for the Advancement of Science, *What We Know: Per- and polyfluoroalkyl substances (PFAS)* (2022)
[*[Link]*](https://www.aaas.org/sites/default/files/2022-07/AAAS-EPI-Center_FactSheet__PFAS_0.pdf?adobe_mc=MCORGID%3D242B6472541199F70A4C98A6%2540AdobeOrg%7CTS%3D1701670717)
  
  
  
# Suggested Economic Model

- Water supplier is a monopolist.

- Water monopolist supplies water quantity ( $q$ ) and water quality ( $s$ ).
  - A higher $q$ means a more quantity of water supplied
  - A higher $s$ means a better quality of water supplied

- A demand for water quantity with water quality is characterized by 

$$
P(q,s) = s\times (1-q),
$$

where $q$ and $s$ are normalized, so that $0<q<1$ and $s>1$.

- Water monopolist's cost of producing water is

$$
C(q,s) = kq + \ell s,
$$
where the marginal cost parameters are $k > 0$ and $0<\ell<\frac{1}{4}$.


## Task 1.
- Draw two demand functions on a $(p, q)$ space on a range of $q\in [0,1]$ with $s_{2} > s_{1}$.

- Provide an economic meaning of $\frac{\partial^{2}p(q,s)}{\partial q \partial s}$.



<br>

## Task 2.

- Solve the water monopolist's problem of maximizing the profit $\Pi$ by choosing $q$ and $s$:

$$
\begin{align}
\max_{q, s}\; \Pi &= R(q,s) - C(q,s)\\
&= s(1-q)q - (kq + \ell s)
\end{align}
$$

- Note that when maximizing the profit, the monopolist does not take the price of water as given, because of the market power she has.

  - Profit maximizing conditions are $\frac{\partial R(q,s)}{\partial q } = \frac{\partial C(q,s)}{\partial q}$ and $\frac{\partial R(q,s)}{\partial s } = \frac{\partial C(q,s)}{\partial s}$

<br>


## Task 3.
- Solve the Social planner's problem of maximizing the social welfare $SW$ by choosing $q$ and $s$:


$$
\begin{align}
\max_{q, s}\; SW &= \int_{0}^{q} s(1-\theta)d\theta - c(q,s)  \\
&= s\left(q-\frac{1}{2}q^{2}\right) - (kq + \ell s)
\end{align}
$$

<br>


## Task 4.

- Compared to the Social planner, does the water monopolist under-supplies water quality $s$? 

- If the water monopolist under-supplies water quality $s$, what policy or policy mix would you consider to make them provide the socially optimal level of water quality?




