---
title: "ECON 340: Classwork 8 - Pigouvian Tax and Clean Technology"
date: 2023-10-18
execute: 
  echo: false
  eval: true
  warning: false
  message: false
---

# Pollution Tax and Clean Technology

Suppose that in the competitive market there are $N$ polluting firms ( $i = 1, 2, \cdots, N$ ) that produces identical goods under the private cost function 
$$
PC(q_{i}) = \frac{1}{2}q_{i}^{2} + q_{i}
$$
where $q_{i}$ and $PC(q_{i})$ are the firm $i$ quantity of output and the private total cost, respectively.

The firms are currently causing environmental pollution in the surrounding area. For all firms, the external cost of this pollution is defined as:

$$
EC(e_{i}) = 4e_{i}
$$
where $e_{i}$ is the firm $i$'s level of pollution emissions.

The firm $i$'s emission level $e_{i}$ is a function of the firm $i$ quantity of output $q_{i}$:
$$
e_{i}\equiv e(q_{i}) = Aq_{i},
$$
where $A > 0$ is the parameter for the firm's abatement technology.

Government forces the firm $i$ to pay a per-unit tax on the emission $e_{i}$.


Let $P$ be the price of the good produced by the firms. The market demand curve for the goods is
$$
D(P) = 20 − 2P.
$$



<br>

## a.

- Taking the price of the good $P$ and the per-unit tax $t$ as given, solve the firm $i$'s profit-maximization problem. 
  - That is to find the profit-maximizing the quantity of output $q_{i}^{*}$

<br><br><br>

## b.

- Since paying pollution tax is costly, the firms are considering to adopt clean technology to reduce emissions. Suppose that the firms are heterogeneous in the sense that each of the firms has a different level of lump-sum investment cost $F_{i}$, where $F_{1} < F_{2} < \cdots < F_{N}$, to adopt the following clean technology (CT):

$$
e_{i}^{CT} = (A-\epsilon)q_{i},
$$
where $A-\epsilon > 0$.


- Taking the price of the good $P$ and the per-unit tax $t$ as given, solve the firm $i$'s profit-maximization problem, in which the firm $i$ chooses (1) the quantity of output $q_{i}$ and whether or not adopting the clean technology. 

<br><br><br>

## c.
- Describe how the tax rate is related to the firms' adoption of the clean technology.

<br><br><br>


