---
title: "ECON 340: Classwork 10 - Mock-up Exam II"
date: 2023-11-15
execute: 
  echo: false
  eval: true
  warning: false
  message: false
---



<br><br><br>


Grand Teton National Park is located 10 minutes away from city Jackson and 20 minutes away from city Teton. Cities Jackson and Teton have 25,000 and 10,000 inhabitants respectively, and residents in both cities have the same income and preferences for national parks. Assume that the cost for an individual to go to a national park is represented by the cost of the time it takes her to get into the park. Also assume that the cost of time for individuals in cities Jackson and Teton is $.50 per minute. You observe that each inhabitant of city Jackson goes to Grand Teton ten times a year while each inhabitant of city Teton goes only five times a year. Assume the following: the only people who go to the park are the residents of cities Jackson and Teton; the cost of running Grand Teton is $1,000,000 a year; and the social discount rate is 1%. Also assume that the park lasts forever.


## Q1a.
Compute the cost per visit to Grand Teton for an inhabitant of each city.

<br>

## Q1b.
Assuming that those two observations (cost per visit and number of visits per inhabitant of city Jackson, and cost per visit and number of visits per inhabitant of city Teton) correspond to two points of the same linear individual demand curve for visits to Grand Teton, derive that demand curve. What is the consumer surplus for inhabitants of each city? What is the total consumer surplus?


<br>

## Q1c.
There is a timber developer who wants to buy Grand Teton to run his business. He is offering $50 million for the park. Should the park be sold?

<br>

