---
title: "ECON 340: Team Project"
author: 
  - Jocelyn Haines
  - Daniel Xu
  - <i>Feedback provided by</i> Byeong-Hak Choe
date: 2023-12-03
execute: 
  echo: false
  eval: true
  warning: false
  message: false
---



- The proposal presents a compelling and relevant research topic for air pollution in relation to essential and non-essential transportation under lockdown policies.

- I would suggest you guys to incorporate **environmental justice** into your study. 

  - Working from home tends to be a luxury afforded only to the privileged or majority group. 

  - Low-paid service sector employees — who are most likely to live in neighborhoods with high level of ambient air pollution — need to work on-site, so that the use of essential transportation would be higher for the minority group.



# Environmental Justice

- **Environmental justice** focuses on ensuring that environmental benefits and burdens are distributed equitably among all communities, particularly marginalized ones. 
  - This perspective could involve exploring how different communities within the five boroughs in NYC or NY state were affected differently by the lockdown and the subsequent changes in air quality. 
  - It could also involve examining whether any post-COVID-19 policies suggested as a result of this study would have equitable impacts across different socio-economic and racial groups. 
  - By integrating environmental justice, the paper could provide a more comprehensive understanding of the lockdown's environmental and social impacts and offer more inclusive policy recommendations. 


## More references
- Consider the following references:
  - Highlight for Zhang et. al. (2021), ["Lockdown skies: Research explores the link between pandemic, pollution and race"](https://www.binghamton.edu/news/story/3315/lockdown-skies-research-explores-the-link-between-pandemic-pollution-and-race)
  - Zhang et. al. (2021), ["Environmental justice and the COVID-19 pandemic: Evidence from New York State"](https://bcdanl.github.io/pdfs/econ-340-daniel-jocelyn-ref.pdf)
  - Highlight for Krupnick et. al. (2023), [Executive Summary for "Prioritizing Justice in New York State Climate Policy: Cleaner Air for Disadvantaged Communities?"](https://www.rff.org/publications/reports/environmental-justice-communities-new-york-state-climate-policy-clcpa/#:~:text=The%20law%20specifically%20directs%20the,and%20to%20“prioritize%20measures%20to)
  - Krupnick et. al. (2023), ["Prioritizing Justice in New York State Climate Policy: Cleaner Air for Disadvantaged Communities?"](https://media.rff.org/documents/Report_23-12_ljA90n6.pdf)
  - OECD (2016), ["The economic consequences of outdoor air pollution"](https://www.oecd.org/environment/indicators-modelling-outlooks/Policy-Highlights-Economic-consequences-of-outdoor-air-pollution-web.pdf)

<br><br>

# A Model of Pollution and Health

## Consumer's Health and Air Pollution

- Let us consider health ( $H$ ) as a function of air pollution, medical care,  and preventive measure to avoid air pollution:
  - $H$: Health
  - $P$: Ambient air pollution level
  - $M$: Medical care
  - $A$: Preventive measure to avoid air pollution (e.g., air filtration)


$$
\begin{align}
H = H(\;M, A, P \;)
\end{align}
$$  

- Assume that medical care $M$ is a function of illness episode $\phi$
  - The longer the illness episode, the more spending on medical care.

$$
\begin{align}
M = M(\phi)
\end{align}
$$

- Assume that illness episode $\phi$ is a function of pollution ( $P$ ) and preventive measure to avoid air pollution ( $A$ )
  - The more spending on avoidance behavior, the shorter the illness episode.
  - The more pollution exposure, the longer the illness episode.


$$
\begin{align}
\phi = \phi(A, P)
\end{align}
$$

- Let us redefine the health function  ( $H$ )


$$
\begin{align}
H &= H(\;M, A, P \;) \\
&= H(\;M(\,\phi(A, P)\,),\, \phi(A, P) \;) \tag{Eq-H}
\end{align}
$$
  

## Consumer's Utility

- Consumer values a numeraire good $x$, leisure time $L$, and health $H$:

$$
\begin{align}
U = x + U_{L}(L) + U_{H}(H)
\end{align}
$$

## Consumer's Budget Constraint

- Consumer has time endowment $T$ and allocates time endowment into leisure time ( $L$ ) and labor time ( $T-L$ )

- Consumer's income $Y$ is non-wage income $I$ plus wage income $w(H)\times(T- L)$, where wage is a function of health.
  - Wage is a function of health, because the healthier, the more productive in the workplace.

$$
\begin{align}
Y = I + w(H)\times(T- L)
\end{align}
$$
- Consumer's budget constraint is then:

$$
\begin{align}
I + w(H)\times(T- L) = X + p_{X}M + p_{A}A
\end{align}
$$

## Utility Maximization

- Given the price of medical care $p_{M}$ and the price of avoidance behavior $p_{A}$, consumer maximizes her utility: 

$$
\begin{align}
\max_{x, L, A, M}\; U &=\, x + U_{L}(L) + U_{H}(\, H(P, M ,A) \,)\tag{P1}\\
\text{subject to }\; I + w(H)[T- L] &= X + p_{X}M + p_{A}A\\
\; H &=  H(M, A ,P)
\end{align}
$$
- For simplicity, here I use a simple form of health function.


- Replacing a numeraire good using the budget constraint gives:

$$
\begin{align}
\max_{L, A, M}\; U &=\, I + w(\,H(M, A ,P)\,)[T- L] - p_{X}M - p_{A}A + U_{L}(L) + U_{H}(\, H(M, A ,P) \,)\tag{P2}\\
\end{align}
$$

## First-Order Conditions

$$
\begin{align}
\frac{\partial U}{\partial L} &= -w(H) + \frac{\partial U_{L}}{\partial L}   = 0\tag{FOC-L}\\
\frac{\partial U}{\partial A} &=  \left(\frac{\partial w}{\partial H} + \frac{\partial U_{H}}{\partial H}\right)\times\frac{\partial H}{\partial A} - p_{A} = 0\tag{FOC-A}\\
\frac{\partial U}{\partial M} &=  \left(\frac{\partial w}{\partial H} + \frac{\partial U_{H}}{\partial H}\right)\times\frac{\partial H}{\partial M} - p_{M}                                                   = 0\tag{FOC-M}
\end{align}
$$

- (FOC-L) describes the standard trade-offs between labor and leisure.
  - At optimum, marginal benefit of enjoying one unit of leisure is equal to wage rate.

- (FOC-A) and (FOC-M) can be combined to yield the following intuitive expression for $MRS_{AM}$, the marginal rate of substitution between $A$ and $M$:


$$
\begin{align}
MRS_{AM} \equiv \frac{\frac{\partial H}{\partial A}}{\frac{\partial H}{\partial M}} = \frac{p_{A}}{p_{M}} \tag{MRS-AM}
\end{align}
$$

- Consumer will give up $MRS_{AM}$ units of $A$ in exchange for 1 additional unit of $M$.

- The rate at which the consumer is willing to trade between two goods is exactly the same as the rate at which consumer can trade these goods in the market, the price ratio. 


## The Effect of Pollution on Health

- Since avoidance behavior and medical care consumption depend on ambient pollution levels, the relationship between health and pollution levels can be expressed as the following total derivative of heath function (Eq-H) with respect to ambient air pollution:

$$
\begin{align}
\frac{d H}{d P} &= \frac{dH}{d\phi} \times\frac{d\phi}{dP}\\
&= \underbrace{\left(\frac{\partial H}{\partial M}\frac{\partial M}{\partial \phi} + \frac{\partial H}{\partial \phi}\right)}_{\frac{dH}{d\phi}} \times \underbrace{\left(\frac{\partial \phi}{\partial P} + \frac{\partial \phi}{\partial A}\frac{\partial A}{\partial P}\right)}_{\frac{d\phi}{dP}}
\end{align}
$$

- The effect of pollution on population health depends on two distinct components:
  - The relationship between pollution and illness ( $\frac{d\phi}{dP}$ )
    - $\frac{\partial \phi}{\partial P}$: The pure biological effect of pollution on illness
    - $\frac{\partial \phi}{\partial A}\times \frac{\partial A}{\partial P}$: The role of avoidance behavior in averting illness episodes by limiting contact with pollutants

  - The degree to which illness is translated into poor health status ( $\frac{dH}{d\phi}$ )
      - $\frac{\partial H}{\partial M}\times \frac{\partial M}{\partial \phi}$: The degree to which medical treatment ameliorates the negative effects of pollution on health
      - $\frac{\partial H}{\partial \phi}$: The degree to which pollution-induced illness episodes are not treated, either because the condition is untreatable or because individuals do not seek treatment for it.

<br><br>

# Task - Modeling for Majority vs. Minority

- The effect of pollution on health would depend on whether a consumer is a member of majority group ( $ma$ ) or a member of minority group ( $mi$ ).
  1. $P_{ma}$ vs. $P_{mi}$: It would be relevant to consider the scenario $P_{ma} < P_{mi}$.
  2. $w_{ma}(H_{ma})$ vs. $w_{mi}(H_{mi})$: 
    - Majority group would have higher wage rate and may continue to earn labor income due to work-from-home policies.
    - Minority group would have lower wage rate and may not be able to earn labor income due to lockdown policies.
  3. $\frac{\partial H}{\partial \phi}$---the degree to which pollution-induced illness episodes are not treated---might be different between the majority and the minority.
    - $\frac{\partial H}{\partial \phi}$ varies by medical condition.
    - Medical condition tends to be worse for the minority than for the majority.
    - $\frac{\partial H}{\partial \phi}$ would capture some of the transient suffering that accrues before medical treatments take effect. 

<br><br>

<!-- # Majority vs. Minority from Zhang et. al. (2021) -->

<!-- - Air quality tends to be far worse in neighborhoods with a higher proportion of low-income and minority populations, since most factories and highways tend to be located in or near these neighborhoods. -->

<!-- - Neighborhoods with a higher proportion of low-income and minority populations possibly could have seen the greatest improvements in air quality during pandemic-related shutdowns, due to the sharp decline in factory production and commercial traffic.  -->

<!-- - But another factor worked in the opposite direction: working from home tends to be a luxury afforded only to the privileged.  -->

<!-- - Low-paid service sector employees — who are most likely to live in these neighborhoods — still needed to work on-site. -->






