---
title: "ECON 340: Homework Assignment 2"
date: 2023-09-12
execute: 
  echo: false
---

# Question 1. Negative Externalities II
Consider a society with just two consumers. Consumer 1 can get positive utility from a positive amount of some activity $h$ that she chooses the level of, but consumer 2 gets negative utility from that activity. We can think of $h$ as some non-market good, for example, "hours" of loud music played by consumer 1, disturbing consumer 2's peace and quiet. Consumer 1 therefore imposes a negative externality on consumer 2. Assume there is no other cost associated with the activity.

Assume that both consumers gain utilities from consuming a numeraire good $x$, whose price is 1, but may have different incomes $Y_{1}$ and $Y_{2}$.

- Consumer 1's utility is $U_{1} = x_{1} + h(4-h)$.
- Consumer 2's utility is $U_{2} = x_{2} - h^{2}$.


<br>

## Q1e.
- Suppose that, instead of a tax or a subsidy, the government introduces a marketable-permit scheme. 
  - It gives consumer 2 a bunch of pieces of paper called "permits," each of which states that the holder of the permit has the legal right to "produce" one unit of $h$. 
  - It then allows consumer 2 to sell those permits to consumer 1 at some uniform price $p_{h}$. 


- Assume that the permit market is competitive.
  - This means that each consumer takes the price $p_{h}$ as given. 
  - You can think of each consumer as "representing" a large number of consumers of the same type.


- Show that the scheme will also achieve the socially optimal outcome $h^{o}$. 


<br>

## Q1f.
- Same question as Q1e, but now the government introduces a marketable-permit scheme that gives a bunch of permits to consumer 1, and then gives consumer 2 an opportunity to buy them away from consumer 1 and "retire" them.

<br>

## Q1g.
- Suppose that, instead of trying to intervene in the market, the government just passes a law giving consumer 2 a clearly defined right to have $h = 0$ (e.g., it imposes a noise ordinance that forbids consumer 1 from playing loud music), but then allows consumer 1 to effectively "bribe" consumer 2 to give up some of that right (i.e., allow some music playing) in exchange for a lump-sum transfer $T$. 

- Show that this, too, will restore social optimality.

<br>

## Q1h.
- Same question as Q1g, but now the government gives consumer 1 a clear legal right to $h^{*}$ (i.e., in our example, a right to play as much loud music as she likes), and then allows consumer 2 to effectively "bribe" consumer 1 to give up some of that right (i.e., cut back on her music playing) in exchange for a lump-sum transfer $T$.


<br><br><br>

# Question 2. Measuring the Benefit of Environmental Quality

Consider the consumer, Amazon, whose utility is described as follows:

$$
\begin{align}
U(x, q) = x^{\frac{2}{3}}q^{\frac{1}{3}}
\end{align}
$$
Amazon values (1) the monetary amount, denoted by $\$x$, that she possesses and (2) the size of the forest area she owns, measured in hectares (ha), represented by $q$.

Suppose Amazon holds $1,000,000,000. She is currently contemplating an ambitious initiative titled "Quadrupling the Amazon Forest," aimed at expanding its forest area. Please respond to the following questions:


## Q2a.
- What amount is Amazon willing to pay (WTP) to expand the forest area to four times its current size?

- What compensation is Amazon willing to accept (WTA) to forego the "Quadrupling the Amazon Forest" project?

<br>

## Q2b.
Are your calculations for WTP and WTA identical or do they differ? Please explain the reasons behind your assessment of their similarity or difference.


<br><br><br>


# Question 3. Travel Cost

Now it is time for your first consulting job as an environmental economist. The Forest Service would like to know whether they should set aside some National Forest land, previously slated to be logged, for hiking. You are helping do a travel-cost analysis to estimate the benefits of the set-aside.

Survey data has been gathered from 500 hikers who visited a forest in a neighboring state. Using a statistical technique called regression analysis, you have controlled for differences in income, employment status, age and other important factors that might affect the number of hiking trips taken. Taking these factors into account, you have developed the following relationship:

|  Cost to get to Hiking Areas | # of Hiking Trips Per Person Per Year  |
|:-----------------:|:--------------------:|
| $20             | 8                   |
| $40             | 6                   |
| $80             | 2                   |

## Q3a.
- Graph the demand curve for hiking trips as a function of the "price"---the travel cost.

<br>

## Q3b.
- Based on demographic information about the people living in the vicinity of the proposed park, you have estimated that 50,000 people will take an average of 4 hiking trips per year. 


- For the average person, calculate: 
  1. The consumer surplus for a single visit to the new park by a visitor with travel costs of $20; 
  2. The total consumer surplus for an average visitor (hint: the area of a triangle is $\frac{1}{2}(B*H)$ ); and 
  3. The total expected consumer surplus per year from the proposed park.  

<br>
