---
title: "ECON 340: Classwork 4"
date: 2023-09-18
---

# Market Equilibrium, Planning Problem, and the Role of Government

- **Market Equilibrium**: In a competitive equilibrium, supply equals demand in every market, and every agent maximizes their utility or profit given market prices. In this state, no one has an incentive to change their behavior, as they are already optimizing given the current prices and allocations. 

- **Social planner**: Let us assume the existence of a *benevolent* social planner who makes all the decisions in the economy. The social planner is benevolent because the social planner's objective is to maximize the social welfare by allocating available resources in the economy. While prices coordinate exchanges between agents in the competitive markets, the social planner does not follow prices when allocating resources.

- **Government**: Government's objective is the same as the social planner's one---maximizing the social welfare. Unlike the social planner, however, government cannot freely allocate available resources in the economy. Instead, government uses policy tools, such as taxes and subsidies, to achieve the socially optimal allocation of resources given the agents' optimizing behaviors.


## Example: Economy with two consumers
Consider a society with just two consumers. Consumer 1 can get positive utility from a positive amount of some activity $h$ that she chooses the level of, but consumer 2 gets negative utility from that activity. We can think of $h$ as some non-market good, for example, "hours" of loud music played by consumer 1, disturbing consumer 2's peace and quiet. Consumer 1 therefore imposes a negative externality on consumer 2. Assume there is no other cost associated with the activity.

Assume that both consumers gain utilities from consuming a numeraire good $x$, whose price is 1, but may have different incomes $Y_{1}$ and $Y_{2}$.

- Consumer 1's utility is $U_{1} = u_{1}(x_{1}, h)$;
- Consumer 2's utility is $U_{2} = u_{2}(x_{2}, h)$.

### Market outcome
- Each consumer's object is to maximize his/her own utility subject to his/her budget constraint.

### Social planner
- Social planner maximizes social welfare subject to resource constraint.

### Market outcome with government policy
- Each consumer's object is to maximize his/her own utility subject to his/her budget constraint.

- Government's object is to maximize social welfare subject to its budget constraint for its policy tools, consumers' budget constraints, and consumers' optimizing behaviors.

