---
title: "ECON 340: Team Project"
author: 
  - Aman Manghi 
  - Dominic Pagano
  - Reo Sakida
  - <i>Feedback provided by</i> Byeong-Hak Choe
date: 2023-12-03
execute: 
  echo: false
  eval: true
  warning: false
  message: false
---

- The proposal presents a compelling and relevant research topic for international cooperation on climate change. 

- I would suggest you guys to incorporate the **Carbon Border Adjustment Mechanism (CBAM)**.


# CBAM

- **Objective**: The primary goal of CBAM is to mitigate **carbon leakage**, which occurs when companies transfer production to countries with looser carbon emission restrictions, undermining domestic climate policies.

- **Function**: CBAM works by imposing a cost (e.g., tariff) on imports of certain goods from countries with less stringent carbon emission controls. Essentially, it levels the playing field for domestic producers who are subject to carbon taxes or emission trading systems.

- **Mechanism**: When goods are imported into a CBAM-implementing country, the importer must buy carbon certificates via  corresponding to the carbon price that would have been paid if the goods had been produced under the importing country's carbon pricing policies. This cost is calculated based on the carbon content of the imported goods.

- **Global Trade and Environment**: CBAM is designed to encourage greener production globally. By making it more expensive to import goods from countries with lax carbon tax or other environmental regulation, it incentivizes other countries to adopt stricter carbon emission regulations.

- **Compliance with International Rules**: A key aspect of CBAM is its need to comply with World Trade Organization (WTO) rules and other international trade laws, ensuring it is not used as a protectionist tool but rather as a genuine effort to combat climate change.

Incorporating CBAM into your study could provide valuable insights into how such mechanisms can complement domestic carbon taxes and contribute to more effective global environmental policies.


# Feedback

- Include more specific examples or case studies.
  - Including descriptive statistics or visualization about time trend of greenhouse gas (GHG) emissions in each country, as well as overall trend of GHG concentration in the globe.

- Provide additional details on the economic model and theoretical analysis approach.

- Consider summarizing the following reference:
  - [Carbon Border Adjustments: Design Elements, Options, and Policy Decisions](https://www.rff.org/publications/reports/carbon-border-adjustments-design-elements-options-and-policy-decisions/)
  - [Border Carbon Adjustments: Background and Developments in the European Union](https://crsreports.congress.gov/product/pdf/R/R47167)
  - [Carbon Border Adjustment Mechanism: A new, green way of pricing carbon in imports to the EU](https://www.eeas.europa.eu/sites/default/files/documents/2023/Carbon%20Border%20Adjustment%20Mechanism.pdf)
  
  


# Suggested Model

- Agents
  - Sweden Consumer
  - Sweden Producer
  - Sweden Government
  - Indian Consumer
  - Indian Producer
  - Indian Government
  - Social Planner (a global version)
  

- **Sweden Consumer** lives in Sweden and chooses how much to consume a Sweden good being sold in Sweden ( $q_{S}$ ) and an Indian good being sold in Sweden ( $\tilde{q}_{I}$ ).
- **Sweden Producer** locates in Sweden and chooses how much to produce a Sweden good being sold in Sweden ( $q_{S}$ ) and a Sweden good being sold in India ( $\tilde{q}_{S}$ ).

- **Indian Consumer** lives in India and chooses how much to consume an Indian good being sold in India ( $q_{I}$ ) and a Sweden good being sold in India ( $\tilde{q}_{S}$ ).
- **Indian Producer** locates in India and chooses how much to produce an Indian good being sold in India ( $q_{I}$ ) and an Indian good being sold in Sweden ( $\tilde{q}_{I}$ ).


- The climate damage in Sweden caused by carbon emissions from Sweden Producer and Indian Producer is denoted by 

$$
D_{S} = D_{S}(q_{S} + \tilde{q}_{S} + q_{I} + \tilde{q}_{I})
$$

- The climate damage in India caused by carbon emissions from Sweden Producer and Indian Producer is denoted by 

$$
D_{I} = D_{I}(q_{S} + \tilde{q}_{S} + q_{I} + \tilde{q}_{I})
$$


<br><br>

## Sweden
### Sweden Consumer

Given the Sweden's income ( $Y_{S}$ ), the price of a Sweden good in Sweden ( $p_{S}$ ), and the price of an Indian good in Sweden ( $\tilde{p}_{I}$ ), **Sweden Consumer** maximizes her utility:
$$
\begin{align}
\max_{q_{S}, \tilde{q}_{I}}\;U_{S} = Y_{S} - p_{S}q_{S} - \tilde{p}_{I}\tilde{q}_{I} + V_{SS}(q_{S}) + V_{SI}(\tilde{q}_{I})
\end{align}
$$


### Sweden Producer

Given the price of a Sweden good in Sweden ( $p_{S}$ ) and the price of a Sweden good in India ( $\tilde{p}_{S}$ ), **Sweden Producer** maximizes her profit:
$$
\begin{align}
\max_{q_{S}, \tilde{q}_{S}}\;\Pi_{S} = p_{S}q_{S} + \tilde{p}_{S}\tilde{q}_{S} - C_{S}( q_{S} + \tilde{q}_{S} ) 
\end{align}
$$

<br><br>

## India
### Indian Consumer

Given the India's income ( $Y_{I}$ ), the price of an Indian good in India ( $p_{I}$ ), and the price of a Sweden good in India ( $\tilde{p}_{S}$ ), **Indian Consumer** maximizes his utility:

$$
\begin{align}
\max_{q_{I}, \tilde{q}_{S}}\;U_{I} = Y_{I} - p_{I}q_{I} - \tilde{p}_{S}\tilde{q}_{S} + V_{II}(q_{I}) + V_{IS}(\tilde{q}_{S})
\end{align}
$$

### Indian Producer

Given the price of an India good in India ( $p_{I}$ ) and the price of an Indian good in Sweden ( $\tilde{p}_{I}$ ), **Indian Producer** maximizes her profit:
$$
\begin{align}
\max_{q_{I}, \tilde{q}_{I}}\;\Pi_{I} = p_{I}q_{I} + \tilde{p}_{I}\tilde{q}_{I} - C_{I}( q_{I} + \tilde{q}_{I} ) 
\end{align}
$$

<br><br>

## Social Planner, a global version

The Social Planner allocates Sweden/Indian goods in Sweden/India maximizes the social welfare, taking into account the climate damages in Sweden and India

$$
\begin{align}
\max_{q_{S}, \tilde{q}_{S}, q_{I}, \tilde{q}_{I}}\; SW &= U_{S} + U_{I} + \Pi_{S} + \Pi_{I} - (D_{S} + D_{I})\\
&=\; Y_{S} + Y_{I}\\&\quad + V_{SS}(q_{S}) + V_{SI}(\tilde{q}_{I}) + V_{II}(q_{I}) + V_{IS}(\tilde{q}_{S})\\&\quad - C_{S}( q_{S} + \tilde{q}_{S} )  - C_{I}( q_{I} + \tilde{q}_{I} )\\&\quad - D_{S}(q_{S} + \tilde{q}_{S} + q_{I} + \tilde{q}_{I}) - D_{I}(q_{S} + \tilde{q}_{S} + q_{I} + \tilde{q}_{I})
\end{align}
$$

# Tasks


## Task 1 - Globally optimal resource allocations
- Derive the first order conditions for the Social Planner's maximization problem, which characterizes the globally optimal resource allocations $\left(\,\left\{q_{S}^{o}, \tilde{q}_{S}^{o}, q_{I}^{o}, \tilde{q}_{I}^{o}\right\}\,\right)$ and determine the globally optimal carbon tax. 

<br>
<br>

## Task 2 - Markets under the Local Carbon Tax System

- Let $t_{SS}$ denote **Swedish Government**'s carbon tax imposed on goods produced by Sweden Producer ( $q_{S}$ and  $\tilde{q}_{S}$ ).

- Let $t_{II}$ denote **Indian Government**'s carbon tax imposed on goods produced by Indian Producer ( $q_{I}$ and  $\tilde{q}_{I}$ ).


- Under the local carbon tax, consider the markets for the following four goods:
  - A Sweden good being sold in Sweden ( $q_{S}$ )
  - An Indian good being sold in Sweden ( $\tilde{q}_{I}$ )
  - An Indian good being sold in India ( $q_{I}$ )
  - A Sweden good being sold in India ( $\tilde{q}_{S}$ )

- Derive the demand and supply curves for each market using the first-order conditions for the Consumers' and the Producers' problems under the local carbon tax.

- Draw the linear demand and supply functions, assuming the quadratic form of utility and cost functions.

- Describe how the carbon taxes shift the supply functions.

<br>
<br>



## Task 3 - Optimal Carbon Tax
- To achieve the globally optimal resource allocations $\left(\,\left\{q_{S}^{o}, \tilde{q}_{S}^{o}, q_{I}^{o}, \tilde{q}_{I}^{o}\right\}\,\right)$, what rate of carbon taxes should each government set?

<br>
<br>




## Task 4 - Hypothetical Scenario

- Suppose the Sweden government imposes the optimal carbon tax that internalizes the global climate damage ( $D = D_{S} + D_{I}$ ), while the Indian government imposes the locally optimal carbon tax that internalizes only the local climate damage ( $D_{I}$ ).

- Design the CBAM that the Sweden government induces the Indian Producer to produce the globally optimal level of the good being sold in Sweden.
  - That is, for the Sweden government to impose tariff $(\,t_{SI}\,)$ on Indian goods being sold in Sweden.


<br>
<br>






