---
title: "ECON 340: Homework Assignment 5"
date: 2023-12-03
execute: 
  echo: false
---

# Question 1. Cost-effective Gunk Control 

Two plants are emitting a uniformly mixed pollutant called gunk into the beautiful sky over Tourist Town.  The city government decides that it can tolerate total emissions of no more than 100 kgs of gunk per day.  Plant G has marginal reduction costs of $100 - 4x$, and is currently polluting at a level of 25, while plant K has marginal reduction costs of $150 - y$, and currently pollutes at a level of 150.  ($x$ and $y$ are the level of emissions at each plant).

## Q1a.
What is the cost effective pollution level for each plant if total pollution must equal 100? Suppose the city government knows marginal reduction costs at the two plants. In this case could the city obtain cost effective pollution reduction using a CAC approach? If so, how? 

<br>

## Q1b.
In reality, why might the city have a hard time getting this information? What are the two "Incentive Based" policies that could be used to get a cost effective reduction of pollution to 100 units, without knowing the MC of the two firms? Be specific. Discuss two advantages each method has over the other.  

<br>

## Q1c.
Suppose the authorities are considering a tradeable emission permit system in which they give half the permits to each firm, or a tax system. If both systems work perfectly, how much will the firms have to pay, in total, for pollution reduction under the two schemes? Could this explain why Tourist Town would be more likely to adopt a permit give-away system? 

<br>

## Q1d.
Several theoretical studies have shown that Incentive Based policies might generate huge cost savings, with the IB approach being as much as 22 times cheaper as a CAC approach. Discuss at least three reasons why Tourist Town might not get such substantial savings in moving from CAC regulation to a marketable permit system.

<br>

## Q1e.
Would a CAC system in Tourist Town generate benefits in the form of either "over-control" or a reduction in hot-spots, relative to an incentive-based approach?  

<br>

## Q1f.
Suppose the marginal benefits of pollution reduction in Tourist Town are constant and equal to $64. (Each unit of pollution reduction brings in one more tourist, who spends $64.). Is 100 units of pollution, obtained cost effectively, an efficient level? If not, will efficiency be achieved through more or less pollution? Why?
