---
title: "ECON 340: Team Project"
author: 
  - Miranda Bartkowiak
  - <i>Feedback provided by</i> Byeong-Hak Choe
date: 2023-12-03
execute: 
  echo: false
  eval: true
  warning: false
  message: false
  fig-cap-location: margin

---

The proposal presents a compelling and significant research topic with a clear objective.  


# Feedback

- Include specific data or examples to quantify the scale of the problem.

- Include a brief summary on the references you have.

- Provide additional details on the economic model and theoretical analysis approach.

  
  
# Suggested Economic Model of Recycling

- Consider using the theoretical model provided in the following reference:
  - Kentaka Aruga, *Environmental and Natural Resource Economics*, Springer (2022) [*[Link]*](https://bcdanl.github.io/pdfs/econ-340-miranda-ref.pdf)
  
  
- Consider the different types of policies using the model in the above reference:
  - Targets for waste reduction
  - Fees incurred by producers
  - Incentives for recycling
  - Banning waste exports to foreign countries 


# FYI webinar

- Building a Career in Sustainability: The Future of the Fashion Industry
  - [*[Link]*](https://www.eventbrite.com/e/building-a-career-in-sustainability-the-future-of-the-fashion-industry-registration-763528112137?aff=emails)
  
  