---
title: "ECON 340: Team Project"
author: 
  - Josh Catanese
  - Orlando Dibaccio
  - Zach Gauronski
  - <i>Feedback provided by</i> Byeong-Hak Choe
date: 2023-12-03
execute: 
  echo: false
  eval: true
  warning: false
  message: false
  fig-cap-location: margin

---

# Feedback

- Include a brief summary on the references you have.
  - You guys chosen excellent references by the way!

- Provide additional details on the economic model and theoretical analysis approach.

- The objectives/problems you guys set requires an empirical analysis. If you guys do not think you can finish it by the due, it is okay to do instead literature review regarding the objectives/problems.


# Suggested Economic Model

- Consider the four economic agents as well as the Social Planner:
  - Power plant
  - Consumer
  - Government
  - Social Planner
  
## Power plant
- Power plant uses either clean energy or dirty energy to produce electricity ($e$).

- Power plant has a continuum of plants, and she can freely adjust its relative proportion of dirty and clean plant, $\gamma$ and $1-\gamma$, respectively.

- Power plant's total cost of producing electricity from dirty/clean energies consist of variable costs ( $C_{d}(e)$ and $C_{c}(e)$ ) and fixed costs ( $F_{c}$ and $F_{d}$ ):

$$
\begin{align}
TC_{d} &= C_{d}(e) + F_{d}\\
TC_{c} &= C_{c}(e) + F_{c}
\end{align}
$$

- Taking the electricity price $s$ as given, the power plant maximizes its profit by choosing how much to produce electricity $e$ and the proportion of dirty energy power plant ( $\gamma \in [0,1]$  ):
$$
\begin{align}
\max_{e, \gamma}\;\Pi_{e} &= \gamma\left(\, s e - TC_{d}(e) \,\right) + (1 - \gamma)\left(\, s e - TC_{c}(e) \,\right)\\
&= se - \gamma\, TC_{d}(e)  - (1 - \gamma)\, TC_{c}(e)
\end{align}
$$

## Consumer
- Taking the electricity price $s$ as given, consumer maximizes its utility by choosing a numeraire good $x$ and an electricity consumption $e$:

$$
\begin{align}
\max_{x, e}\;U &= x + v(e)\\
\text{subject to }\; Y &= x + se
\end{align}
$$

The above problem is equivalent to:
$$
\begin{align}
\max_{e}\;U &= Y - se + v(e)\\
\end{align}
$$

## Electricity Market

In the electricity market, the electricity price $s$ is such that the supply and the demand for electricity are met:

$$
v'(e) = \gamma C_{d}'(e) + (1 - \gamma) C_{c}'(e)
$$


## Social planner
- Social planner maximizes social welfare, which takes into account the damage caused by greenhouse gas emissions from dirty power plant, as a function of $\gamma$

$$
\begin{align}
\max_{e,\gamma}\;SW &= \Pi_{e} + U - D\\
&= Y + v(e) - \gamma\, TC_{d}(e)  - (1 - \gamma)\, TC_{c}(e)  - D(\gamma),
\end{align}
$$
where the damage $D(\gamma)$ increases with $\gamma$ at an increasing rate.


## Government
- Government can consider various policies:
  - Tax dirty power plants
  - Subsidy clean power plants
  - Setting emission standards to dirty power plants


## Modeling ideas
- For simplicity, here I abstract away from firm's productions and emissions. Instead, I focus on only power plant and consumer.
- If needed, you guys can always modify the model.





