project:
  type: website
  output-dir: "."
  
website:
  title: "Geneseo DANL"
  page-footer: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2023"
  reader-mode: false
  navbar:
    pinned: true
    left:
      - text: about me
        href: cv.qmd
      - text: "danl 200 lec"
        menu:
        - text: "lecture 01 - syllabus"
          href: lec/DANL200_Lec01_20230124.html
        - text: "lecture 02 - r basic"
          href: lec/DANL200_Lec02_20230126.html
        - text: "lecture 03 - r basic, ggplot"
          href: lec/DANL200_Lec03_20230131.html
        - text: "lecture 04 - ggplot"
          href: lec/DANL200_Lec04_20230202.html
        - text: "lecture 05 - ggplot"
          href: lec/DANL200_Lec05_20230207.html
        - text: "lecture 06 - ggplot"
          href: lec/DANL200_Lec06_20230209.html
        - text: "lecture 07 - ggplot"
          href: lec/DANL200_Lec07_20230214.html
        - text: "lecture 08 - ggplot"
          href: lec/DANL200_Lec08_20230216.html
        - text: "lecture 09 - ggplot, visualization"
          href: lec/DANL200_Lec09_20230221.html
      - text: "danl 200 lab"
        menu:
        - text: hw 1q
          href: DANL200_hw1q.qmd
      - text: danl 210 lec
        menu:
        - text: "lecture 01 - syllabus"
          href: lec/DANL210_Lec01_20230124.html
        - text: "lecture 02 - python basic"
          href: lec/DANL210_Lec02_20230126.html
        - text: "lecture 03 - python basic"
          href: lec/DANL210_Lec03_20230131.html
        - text: "lecture 04 - python basic, pandas"
          href: lec/DANL210_Lec04_20230202.html
        - text: "lecture 05 - pandas"
          href: lec/DANL210_Lec05_20230207.html
        - text: "lecture 06 - pandas"
          href: lec/DANL210_Lec06_20230209.html
        - text: "lecture 07 - pandas"
          href: lec/DANL210_Lec07_20230214.html
        - text: "lecture 08 - pandas"
          href: lec/DANL210_Lec08_20230216.html
        - text: "lecture 09 - pandas"
          href: lec/DANL210_Lec09_20230221.html
      - text: "danl 210 lab"
        menu:
        - text: hw 1q
          href: DANL210_hw1q.qmd    
        - text: lab 1q
          href: https://bcdanl.github.io/DANL210_lab1q_v2.html
      - text: "danl 310 lec"
        menu:
        - text: "lecture 01 - syllabus"
          href: lec/DANL310_Lec01_20230124.html
        - text: "lecture 02 - github website, rmarkdown"
          href: lec/DANL310_Lec02_20230126.html
        - text: "lecture 03 - rmarkdown"
          href: lec/DANL310_Lec03_20230131.html
        - text: "lecture 04 - ggplot"
          href: lec/DANL310_Lec04_20230202.html
        - text: "lecture 05 - ggplot"
          href: lec/DANL310_Lec05_20230207.html
        - text: "lecture 06 - ggplot"
          href: lec/DANL310_Lec06_20230209.html
        - text: "lecture 07 - ggplot"
          href: lec/DANL310_Lec07_20230214.html
        - text: "lecture 08 - ggplot"
          href: lec/DANL310_Lec08_20230216.html
        - text: "lecture 09 - ggplot"
          href: lec/DANL310_Lec09_20230221.html
      - text: "danl 310 lab"
        menu:
        - text: hw 1q
          href: DANL310_hw1q.qmd

format:
  html:
    theme:
      light: flatly
      dark: [darkly, theme-dark.scss]
    # mainfont: Georgia, serif;
    mainfont: Gill Sans, sans-serif;
    toc: true
    include-after-body: target_blank.html
