project:
  type: website
  output-dir: "."
  
website:
  title: "&nbsp;B.H. CHOE"
  favicon: img/favicon.ico
  description: 'A collection of data analytics course contents by Byeong-Hak Choe'
  reader-mode: false
  back-to-top-navigation: true
  
  navbar:
    background: "#003896"
    # foreground: "#0149ab"
    
    logo: img/geneseo-logo-with-suny.jpg
    pinned: true
    left:
      - text: "DANL200: Lecture"
        href: danl-200-listing-lec.qmd
      - text: Classwork
        href: danl-200-listing-cw.qmd
      - text: Homework
        href: danl-200-listing-hw.qmd
        
      - text: "|"
        url: https://bcdanl.github.io
        target: _self
      
      - text: "DANL210: Lecture"
        href: danl-210-listing-lec.qmd
      - text: Classwork
        href: danl-210-listing-cw.qmd
      - text: Homework
        href: danl-210-listing-hw.qmd
        
      
    # right:
    #   - text: About
    #     href: cv/cv.qmd

        

  page-footer: 
    center: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2024"
    # foreground: dark
    # background: '#9b4e55' 
    
format:
  html: 
    theme:
      light: [flatly] # flatly litera sandstone
      dark: [darkly, theme-dark.scss] # darkly cyborg slate solra superhero
    css: [styles.css, assets/css/font.css] # , font.css
    highlight-style: atom-one # espresso   tango
    mainfont:  sans-serif; serif; ui-sans-serif  # Gill Sans, sans-serif;
    toc: true
    include-after-body: target_blank.html
