project:
  type: website
  output-dir: "."
  
website:
  title: "B.H. CHOE"
  page-footer: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2023"
  reader-mode: false
  navbar:
    pinned: true
    left:
      - text: about
        href: cv.qmd
      - text: danl200-lec
        menu:
        - text: lecture 03 - basics in r
          href: lec/danl-200-lec-03-2023-0901.html
        - text: lecture 02 - r, rstudio, tidyverse
          href: lec/danl-200-lec-02-2023-0830.html
        - text: lecture 01 - syllabus
          href: lec/danl-200-lec-01-2023-0828.html
      - text: econ340-lec
        menu:
        - text: lecture 03 - social welfare
          href: lec/econ-340-lec-03-2023-0901.html
        - text: lecture 02 - climate change, social welfare
          href: lec/econ-340-lec-02-2023-0830.html
        - text: lecture 01 - syllabus
          href: lec/econ-340-lec-01-2023-0828.html
      - text: econ340-ex
        menu:
        - text: ex - social welfare and landfills
          href: exercises/econ340-class-exercise-2023-0901.qmd
        
format:
  html:
    theme:
      light: [flatly]
      dark: [darkly, theme-dark.scss]
    css: styles.css
    # mainfont: Georgia, serif;
    mainfont: Gill Sans, sans-serif;
    toc: true
    include-after-body: target_blank.html
