project:
  type: website 
  output-dir: "."
  
website:
  title: "B.H. CHOE&nbsp;&nbsp;&nbsp;"
  favicon: img/favicon.ico
  description: 'A collection of data analytics course contents by Byeong-Hak Choe'
  reader-mode: false
  back-to-top-navigation: true

  navbar:
    background: "#1c4982"
    logo: img/geneseo-logo-squared.png
    pinned: true

  page-footer: 
    border: false
    center: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2024"
    # foreground: dark
    # background: '#9b4e55' 
    
format:
  html: 
    grid:
      margin-width: 400px
      sidebar-width: 275px
    link-external-newwindow: true
    theme:
      light: [flatly]  # flatly litera sandstone 'assets/scss/light.scss'
      dark: [darkly, theme-dark.scss] # darkly cyborg slate solra superhero
    css: [styles.css, assets/css/font.css] # , font.css
    highlight-style: atom-one # espresso   tango
    mainfont:  sans-serif; serif; ui-sans-serif  # Gill Sans, sans-serif;
    toc: true
    # include-after-body: [target-blank.html]
