project:
  type: website
  output-dir: "."
  
website:
  title: "B.H. CHOE"
  page-footer: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2023"
  reader-mode: false
  navbar:
    pinned: true
    left:
      - text: about
        href: cv.qmd
      - text: danl200-lec
        menu:
        - text: "lecture 01 - syllabus"
          href: DANL200_Lec01_20230124.html
        - text: "lecture 02 - r basic"
          href: DANL200_Lec02_20230126.html
        - text: "lecture 03 - r basic, ggplot"
          href: DANL200_Lec03_20230131.html
        - text: "lecture 04 - ggplot"
          href: DANL200_Lec04_20230202.html
        - text: "lecture 05 - ggplot"
          href: DANL200_Lec05_20230207.html
        - text: "lecture 06 - ggplot"
          href: DANL200_Lec06_20230209.html
        - text: "lecture 07 - ggplot"
          href: DANL200_Lec07_20230214.html
        - text: "lecture 08 - ggplot"
          href: DANL200_Lec08_20230216.html
        - text: "lecture 09 - ggplot, visualization"
          href: DANL200_Lec09_20230221.html
        - text: "lecture 10 - visualization"
          href: DANL200_Lec10_20230223.html
        - text: "lecture 11 - visualization, filter"
          href: DANL200_Lec11_20230302.html
        - text: "lecture 12 - filter, arrange, select"
          href: DANL200_Lec12_20230307.html
        - text: "lecture 13 - select, mutate"
          href: DANL200_Lec13_20230309.html
      - text: danl200-lab
        menu:
        - text: hw1-q
          href: DANL200_hw1q.qmd
        - text: hw1-a
          href: DANL200_hw1a.qmd
        - text: lab1-q
          href: DANL200_lab1q.qmd
        - text: lab1-a
          href: DANL200_lab1a.qmd
        - text: hw2-q
          href: DANL200_hw2q.qmd  
          
      - text: danl210-lec
        menu:
        - text: "lecture 01 - syllabus"
          href: DANL210_Lec01_20230124.html
        - text: "lecture 02 - python basic"
          href: DANL210_Lec02_20230126.html
        - text: "lecture 03 - python basic"
          href: DANL210_Lec03_20230131.html
        - text: "lecture 04 - python basic, pandas"
          href: DANL210_Lec04_20230202.html
        - text: "lecture 05 - pandas"
          href: DANL210_Lec05_20230207.html
        - text: "lecture 06 - pandas"
          href: DANL210_Lec06_20230209.html
        - text: "lecture 07 - pandas"
          href: DANL210_Lec07_20230214.html
        - text: "lecture 08 - pandas"
          href: DANL210_Lec08_20230216.html
        - text: "lecture 09 - pandas"
          href: DANL210_Lec09_20230221.html
        - text: "lecture 10 - eda"
          href: DANL210_Lec10_20230223.html
        - text: "lecture 11 - seaborn"
          href: DANL210_Lec11_20230302.html
        - text: "lecture 12 - seaborn, agg"
          href: DANL210_Lec12_20230307.html
        - text: "lecture 13 - agg"
          href: DANL210_Lec13_20230309.html
      - text: danl210-lab
        menu:
        - text: hw1-q
          href: DANL210_hw1q.qmd    
        - text: hw1-a
          href: DANL210_hw1a.qmd
        - text: lab1-q
          href: DANL210_lab1q_v3.qmd
        - text: lab1-a
          href: DANL210_lab1a.qmd
        - text: lab2-q
          href: DANL210_lab2q.qmd   
        - text: lab2-a
          href: DANL210_lab2a.qmd   
        - text: hw2-q
          href: DANL210_hw2q.qmd  
      - text: danl310-lec
        menu:
        - text: "lecture 01 - syllabus"
          href: DANL310_Lec01_20230124.html
        - text: "lecture 02 - github website, rmarkdown"
          href: DANL310_Lec02_20230126.html
        - text: "lecture 03 - rmarkdown"
          href: DANL310_Lec03_20230131.html
        - text: "lecture 04 - ggplot"
          href: DANL310_Lec04_20230202.html
        - text: "lecture 05 - ggplot"
          href: DANL310_Lec05_20230207.html
        - text: "lecture 06 - ggplot"
          href: DANL310_Lec06_20230209.html
        - text: "lecture 07 - ggplot"
          href: DANL310_Lec07_20230214.html
        - text: "lecture 08 - ggplot"
          href: DANL310_Lec08_20230216.html
        - text: "lecture 09 - ggplot"
          href: DANL310_Lec09_20230221.html
        - text: "lecture 10 - ggplot"
          href: DANL310_Lec10_20230223.html
        - text: "lecture 11 - ggplot"
          href: DANL310_Lec11_20230302.html
        - text: "lecture 12 - work with model"
          href: DANL310_Lec12_20230307.html
        - text: "lecture 13 - color, theme"
          href: DANL310_Lec13_20230309.html
      - text: danl310-lab
        menu:
        - text: hw1-q
          href: DANL310_hw1q.qmd
        - text: hw1-a
          href: DANL310_hw1a.qmd
        - text: hw2-q
          href: DANL310_hw2q.qmd
      - text: ml-lab
        menu:
        - text: linear regression
          href: mba-ch1-lm.qmd
        - text: logistic regression
          href: mba-ch1-logit.qmd
        - text: regularization
          href: mba-ch3-regularization.qmd
        - text: "model selection"
          # href: mba-ch1-lm.qmd
        - text: "double ml"
          # href: mba-ch1-lm.qmd
        - text: "trees and forests"
          # href: mba-ch1-lm.qmd
        - text: "classification"
          # href: mba-ch1-lm.qmd
        - text: "clustering"
          # href: mba-ch1-lm.qmd
        - text: "principal component analysis"
          # href: mba-ch1-lm.qmd
format:
  html:
    theme:
      light: [flatly]
      dark: [darkly, theme-dark.scss]

    # mainfont: Georgia, serif;
    mainfont: Gill Sans, sans-serif;
    toc: true
    include-after-body: target_blank.html
