project:
  type: website
  output-dir: "."
  
website:
  title: "B.H. CHOE"
  page-footer: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2023"
  reader-mode: false
  navbar:
    pinned: true
    left:
      - text: about
        href: cv.qmd
        
format:
  html:
    theme:
      light: [flatly]
      dark: [darkly, theme-dark.scss]
    css: styles.css
    # mainfont: Georgia, serif;
    mainfont: Gill Sans, sans-serif;
    toc: true
    include-after-body: target_blank.html
