project: 
  type: website
  output-dir: "."
  
website:
  title: "B.H. CHOE&nbsp;&nbsp;&nbsp;"
  favicon: img/favicon.ico
  description: 'A collection of data analytics course contents by Byeong-Hak Choe'
  reader-mode: false
  back-to-top-navigation: true
  # page-navigation: true

  navbar:
    background: "#194493"  # "#003896"
    # foreground: "#0149ab"
    
    logo: img/geneseo-logo-square.png
    pinned: true
      
    right:
      - text: DANL 200 - Lecture Board
        href: listing-danl-qa-200.qmd
      - text: "||"
        url: https://bcdanl.github.io
      - text: DANL 210 - Lecture Board
        href: listing-danl-qa-210.qmd
      - text: " "

  sidebar:
    style: docked
    search: false
    collapse-level: 0
    pinned: true
    border: true
    # type: light
    contents:
      - section: <font size ="5"><b>DANL 200&ensp;&ensp;</b></font>
        contents:
        - text: <font size ="5">Lecture&ensp;&ensp; </font>
          href: listing-danl-lec-200.qmd
        - text: <font size ="5">Classwork&ensp;&ensp; </font>
          href: listing-danl-cw-200.qmd
        - text: <font size ="5">Homework&ensp;&ensp; </font>
          href: listing-danl-hw-200.qmd

      - section: <font size ="2">&ensp;&ensp; </font>
      
      - section: <font size ="5"><b>DANL 210&ensp;&ensp;</b></font>
        contents:
        - text: <font size ="5">Lecture&ensp;&ensp; </font>
          href: listing-danl-lec-210.qmd
        - text: <font size ="5">Classwork&ensp;&ensp; </font>
          href: listing-danl-cw-210.qmd
        - text: <font size ="5">Homework&ensp;&ensp; </font>
          href: listing-danl-hw-210.qmd

  page-footer: 
    center: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2024"
    # foreground: dark
    # background: '#9b4e55' 
    
format:
  html: 
    link-external-newwindow: true
    theme:
      light: [flatly]  # flatly litera sandstone 'assets/scss/light.scss'
      dark: [darkly, theme-dark.scss] # darkly cyborg slate solra superhero
    css: [styles.css, assets/css/font.css] # , font.css
    highlight-style: atom-one # espresso   tango
    mainfont:  sans-serif; serif; ui-sans-serif  # Gill Sans, sans-serif;
    toc: true
    # include-after-body: [target-blank.html]
