project:
  type: website
  output-dir: "."
  
website:
  title: B.H. CHOE
  reader-mode: false
  navbar:
    # background: "#a4c5eb"
    # foreground: "#0149ab"
    
    # logo: img/logo-title-slide.png
    pinned: true
    left:
      - text: About
        href: cv.qmd
        
      - text: DANL 200 - Lecture
        menu:
        - text: 39 - factor, string
          href: lec/danl-200-lec-39-2023-1211.html
        - text: 38 - quarto, relational data
          href: lec/danl-200-lec-38-2023-1208.html
        - text: 37 - quarto, relational data
          href: lec/danl-200-lec-37-2023-1206.html
        - text: 36 - quarto, tidy data, pivoting
          href: lec/danl-200-lec-36-2023-1204.html
        - text: 35 - quarto, tidy data, pivoting
          href: lec/danl-200-lec-35-2023-1201.html
        - text: 34 - quarto
          href: lec/danl-200-lec-34-2023-1129.html
        - text: 33 - r project, git, github, and quarto
          href: lec/danl-200-lec-33-2023-1127.html
        - text: 32 - installing tools for the project
          href: lec/danl-200-lec-32-2023-1115.html
        - text: 31 - installing tools for the project
          href: lec/danl-200-lec-31-2023-1113.html
        - text: 30 - grouped mutate/filter/slice
          href: lec/danl-200-lec-30-2023-1110.html
        - text: 29 - summarize
          href: lec/danl-200-lec-29-2023-1108.html
        - text: 28 - summarize
          href: lec/danl-200-lec-28-2023-1106.html
        - text: 27 - summarize
          href: lec/danl-200-lec-27-2023-1103.html
        - text: 26 - summarize
          href: lec/danl-200-lec-26-2023-1101.html
        - text: 25 - summarize
          href: lec/danl-200-lec-25-2023-1030.html
        - text: 24 - mutate, summarize
          href: lec/danl-200-lec-24-2023-1027.html
        - text: 23 - mutate
          href: lec/danl-200-lec-23-2023-1025.html
        - text: 22 - rename, relocate, mutate
          href: lec/danl-200-lec-22-2023-1023.html
        - text: 21 - arrange, select, mutate
          href: lec/danl-200-lec-21-2023-1020.html
        - text: 20 - filter, arrange, select
          href: lec/danl-200-lec-20-2023-1018.html
        - text: 19 - filter
          href: lec/danl-200-lec-19-2023-1016.html
        - text: 18 - filter
          href: lec/danl-200-lec-18-2023-1013.html
        - text: 17 - midterm 1 review
          href: ex/danl200-midterm-1-q-v1.qmd
        - text: 16 - data viz
          href: lec/danl-200-lec-16-2023-1004.html
        - text: 15 - stat, position, coordnate
          href: lec/danl-200-lec-15-2023-1002.html
        - text: 14 - data viz, geoms, stat
          href: lec/danl-200-lec-14-2023-0929.html
        - text: 13 - geoms, stat
          href: lec/danl-200-lec-13-2023-0927.html
        - text: 12 - geoms, stat
          href: lec/danl-200-lec-12-2023-0925.html
        - text: 11 - facets, geoms
          href: lec/danl-200-lec-11-2023-0922.html
        - text: 10 - aesthetic mapping, facets, geoms
          href: lec/danl-200-lec-10-2023-0920.html
        - text: 09 - aesthetic mapping
          href: lec/danl-200-lec-09-2023-0918.html
        - text: 08 - data visualization
          href: lec/danl-200-lec-08-2023-0915.html
        - text: 07 - basics in r; data visualization
          href: lec/danl-200-lec-07-2023-0913.html
        - text: 06 - basics in r
          href: lec/danl-200-lec-06-2023-0911.html
        - text: 05 - basics in r
          href: lec/danl-200-lec-05-2023-0908.html
        - text: 04 - basics in r
          href: lec/danl-200-lec-04-2023-0906.html
        - text: 03 - basics in r
          href: lec/danl-200-lec-03-2023-0901.html
        - text: 02 - r; rstudio; tidyverse
          href: lec/danl-200-lec-02-2023-0830.html
        - text: 01 - syllabus
          href: lec/danl-200-lec-01-2023-0828.html
          
      - text: DANL 399 - Lecture
        menu:
        - text: 10 - interactive plots
          href: lec/danl-399-lec-10-2023-1204.html 
        - text: 09 - draw maps
          href: lec/danl-399-lec-09-2023-1120.html 
        - text: 08 - add labels, make notes, refine your plots
          href: lec/danl-399-lec-08-2023-1030.html 
        - text: 07 - graph tables, add labels, make notes, refine your plots
          href: lec/danl-399-lec-07-2023-1023.html 
        - text: 06 - graph tables, add labels, make notes
          href: lec/danl-399-lec-06-2023-1016.html 
        - text: 05 - show the right numbers
          href: lec/danl-399-lec-05-2023-1011.html
        - text: 04 - show the right numbers
          href: lec/danl-399-lec-04-2023-0925.html
        - text: 03 - data visualization
          href: lec/danl-399-lec-03-2023-0918.html
        - text: 02 - installing the tools; quarto; data viz
          href: lec/danl-399-lec-02-2023-0911.html
        - text: 01 - syllabus; installing the tools
          href: lec/danl-399-lec-01-2023-0906.html

      - text: ECON 340 - Lecture
        menu:
        - text: 37 - incentive-based regulation
          href: lec/econ-340-lec-37-2023-1211.html
        - text: 36 - incentive-based regulation
          href: lec/econ-340-lec-36-2023-1204.html
        - text: 35 - incentive-based regulation
          href: lec/econ-340-lec-35-2023-1201.html
        - text: 34 - incentive-based regulation
          href: lec/econ-340-lec-34-2023-1129.html
        - text: 33 - incentive-based regulation
          href: lec/econ-340-lec-33-2023-1127.html
        - text: 32 - sustainability standard
          href: lec/econ-340-lec-32-2023-1115.html
        - text: 31 - sustainability standard
          href: lec/econ-340-lec-31-2023-1113.html
        - text: 30 - sustainability standard
          href: lec/econ-340-lec-30-2023-1110.html
        - text: 29 - sustainability standard
          href: lec/econ-340-lec-29-2023-1108.html
        - text: 28 - sustainability standard
          href: lec/econ-340-lec-28-2023-1106.html
        - text: 27 - safety standard
          href: lec/econ-340-lec-27-2023-1103.html
        - text: 26 - safety standard
          href: lec/econ-340-lec-26-2023-1101.html
        - text: 25 - safety standard
          href: lec/econ-340-lec-25-2023-1030.html
        - text: 24 - safety standard
          href: lec/econ-340-lec-24-2023-1027.html
        - text: 23 - double dividend, benefit-cost analysis
          href: lec/econ-340-lec-23-2023-1025.html
        - text: 22 - employment impacts of envrionemtal protection, double dividend
          href: lec/econ-340-lec-22-2023-1023.html
        - text: 21 - productivity impacts of envrionemtal protection
          href: lec/econ-340-lec-21-2023-1020.html
        - text: 20 - costs of envrionemtal protection
          href: lec/econ-340-lec-20-2023-1018.html
        - text: 19 - value of life, costs of envrionemtal protection
          href: lec/econ-340-lec-19-2023-1016.html
        - text: 18 - hedonic regression, value of life
          href: lec/econ-340-lec-18-2023-1013.html
        - text: 17 - midterm 1 review
          href: ex/econ340-midterm-1-q.qmd
        - text: 16 - hw 2 review
          href: ex/econ340-hw-2-a.qmd
        - text: 15 - risk assessment, contingent valuation, travel cost
          href: lec/econ-340-lec-15-2023-1002.html
        - text: 14 - wtp-wta, risk assessment
          href: lec/econ-340-lec-14-2023-0929.html
        - text: 13 - cost-benefit analysis in practice, wtp-wta
          href: lec/econ-340-lec-13-2023-0927.html
        - text: 12 - coase theorem, cost-benefit analysis in practice
          href: lec/econ-340-lec-12-2023-0925.html
        - text: 11 - hw 1 review
          href: ex/econ340-hw-1-a.qmd
        - text: 10 - marginal analysis
          href: lec/econ-340-lec-10-2023-0920.html
        - text: 09 - pareto efficiency
          href: lec/econ-340-lec-09-2023-0918.html
        - text: 08 - open access problems; public goods problems
          href: lec/econ-340-lec-08-2023-0915.html
        - text: 07 - open access problems; public goods problems
          href: lec/econ-340-lec-07-2023-0913.html
        - text: 06 - externalities
          href: lec/econ-340-lec-06-2023-0911.html
        - text: 05 - social welfare; externalities
          href: lec/econ-340-lec-05-2023-0908.html
        - text: 04 - social welfare; externalities
          href: lec/econ-340-lec-04-2023-0906.html
        - text: 03 - social welfare
          href: lec/econ-340-lec-03-2023-0901.html
        - text: 02 - climate change; social welfare
          href: lec/econ-340-lec-02-2023-0830.html
        - text: 01 - syllabus
          href: lec/econ-340-lec-01-2023-0828.html

        
  sidebar:
    title: <b>Exercises</b>
    style: "docked"
    search: true
    background: dark
    foreground: light
    collapse-level: 1
    pinned: true
    border: true
    # type: light
    contents:
      - section: <font size ="6" color = "white">Classwork</font>
      - text: "---"
      - section: <font size ="4">Data Analytics 200&ensp;&ensp; </font>
        contents:
        - text: 11 - joining
          href: ex/danl200-cw-11.qmd
        - text: 10 - pivoting
          href: ex/danl200-cw-10.qmd
        - text: 09 - data transformation - nyc dogs
          href: ex/danl200-cw-9.qmd
        - text: 08 - data transformation - climate finance
          href: ex/danl200-cw-8.qmd
        - text: 07 - summarize, group_by
          href: ex/danl200-cw-7.qmd
        - text: 06 - filter, arrange, select, mutate
          href: ex/danl200-cw-6.qmd
        - text: 05 - past hw - fall 2022, danl200-hw1
          href: ex/danl200-cw-5.qmd
        - text: 04 - past hw - spring 2023, danl200-hw1
          href: ex/danl200-cw-4.qmd
        - text: 03 - ggplot - geometric objects, stat, position
          href: ex/danl200-cw-3.qmd
        - text: 02 - ggplot - first step, aethetic mapping, facets
          href: ex/danl200-cw-2.qmd
        - text: 01 - Working with data.frame
          href: ex/danl200-cw-1.qmd
      - text: "---"
      - section: <font size ="4">Data Analytics 399&ensp;&ensp;</font>
        contents:
        - text: 01 - show the right numbers
          href: ex/danl399-cw-1.qmd
      - text: "---"
      - section: <font size ="4">Economics 340&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;</font>
        contents:
        - text: 11 - p vs. q
          href: ex/econ340-cw-11.qmd
        - text: 10 - Mockup Exam 2
          href: ex/econ340-cw-10-v2.qmd
        - text: 09 - Pigouvian Tax - general form
          href: ex/econ340-cw-9.qmd
        - text: 08 - Pigouvian tax and clean technology
          href: ex/econ340-cw-8.qmd
        - text: 07 - Economic modeling
          href: ex/econ340-cw-7.qmd
        - text: 06 - Mockup Exam 1
          href: ex/econ340-cw-6.qmd
        - text: 05 - Lagrangian method
          href: ex/econ340-cw-5.qmd
        - text: 04 - Market equilibrium, social planner, and government
          href: ex/econ340-cw-4.qmd
        - text: 03 - Public goods game
          href: ex/econ340-cw-3.qmd
        - text: 02 - Utilty maximization
          href: ex/econ340-cw-2.qmd
        - text: 01 - Social welfare and landfills
          href: ex/econ340-cw-1.qmd
          
      - section: <font size ="6"> &nbsp; </font>
      
      - section: <font size ="6" color = "white">Homework</font>
      - text: "---"
      - section: <font size ="4">Data Analytics 200&ensp;&ensp;</font>
        contents:
        - text: 06 - Midterm II - Make-up - Review
          href: ex/danl200-midterm-2-makeup-q.qmd
        - text: 06 - Midterm II - Review
          href: ex/danl200-midterm-2-q.qmd
        - text: 05 - HW 5 - Quarto website, NFL data analysis
          href: ex/danl200-hw-5.qmd
        - text: 04 - HW 4 - Data transformation
          href: ex/danl200-hw-4.qmd
        - text: 04 - HW 3 - Data transformation
          href: ex/danl200-hw-3.qmd
        - text: 03 - Midterm I - Review
          href: ex/danl200-midterm-1-a-v1.qmd
        - text: 02 - HW 2 - Review
          href: ex/danl200-hw-2-a.qmd
        - text: 02 - HW 2 - Summary statistics; data visualization
          href: ex/danl200-hw-2.qmd
        - text: 01 - HW 1 - Review
          href: ex/danl200-hw-1-a.qmd
        - text: 01 - HW 1 - R basics; data visualization
          href: ex/danl200-hw-1.qmd
      - text: "---"
      - section: <font size ="4">Data Analytics 399&ensp;&ensp;</font>
        contents:
        - text: 05 - HW 4 - Map visualization
          href: ex/danl399-hw-4.qmd
        - text: 04 - Midterm Exam
          href: ex/danl-399-midterm.qmd
        - text: 03 - HW 3 - data visualization
          href: ex/danl399-hw-3.qmd
        - text: 02 - HW 2 - data visualization
          href: ex/danl399-hw-2.qmd
        - text: 01 - HW 1 - data visualization
          href: ex/danl399-hw-1.qmd
      - text: "---"
      - section: <font size ="4">Economics 340&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;</font>
        contents:
        - text: 05 - HW 5 - Incentive-based regulation
          href: ex/econ340-hw-5.qmd
        - text: 04 - HW 4 - Safety standard and sustainability Standard
          href: ex/econ340-hw-4.qmd
        - text: 04 - HW 3 - Public good provision, VSL
          href: ex/econ340-hw-3-sol.qmd
        - text: 03 - Midterm I - Review
          href: ex/econ340-midterm-1-a.qmd
        - text: 03 - Midterm I
          href: ex/econ340-midterm-1-q.qmd
        - text: 02 - HW 2 - Review
          href: ex/econ340-hw-2-a.qmd
        - text: 02 - HW 2 - Negative externalities II; cost-benefit analysis
          href: ex/econ340-hw-2.qmd
        - text: 01 - HW 1 - Review
          href: ex/econ340-hw-1-a.qmd
        - text: 01 - HW 1 - Negative externalities I; the tradegy of the commons
          href: ex/econ340-hw-1.qmd
  
  page-footer: 
    center: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2023"
    # foreground: dark
    # background: '#9b4e55'
    
format:
  html: 
    theme:
      light: [yeti]
      dark: [solar, theme-dark.scss]
    css: [styles.css] # , font.css
    highlight-style: atom-one # espresso   tango
    mainfont:  sans-serif; serif; ui-sans-serif  # Gill Sans, sans-serif;
    toc: true
    include-after-body: target_blank.html
