project:
  type: website
  output-dir: "."
  
website:
  title: B.H. CHOE
  reader-mode: false
  navbar:
    # background: "#a4c5eb"
    # foreground: "#0149ab"
    
    # logo: img/logo-title-slide.png
    pinned: true
    left:
      - text: "DANL200: Lecture"
        href: danl-200-listing-lec.qmd
      - text: Classwork
        href: danl-200-listing-cw.qmd
      - text: Homework
        href: danl-200-listing-hw.qmd
      
    
    right:
      - text: "DANL210: Lecture"
        href: danl-210-listing-lec.qmd
      - text: Classwork
        href: danl-200-listing-cw.qmd
      - text: Homework
        href: danl-200-listing-hw.qmd
      - text: " "
      - text: " "
      
    # right:
    #   - text: About
    #     href: cv/cv.qmd

        

  page-footer: 
    center: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2023"
    # foreground: dark
    # background: '#9b4e55'
    
format:
  html: 
    theme:
      light: [flatly]
      dark: [darkly, theme-dark.scss]
    css: [styles.css, assets/css/font.css] # , font.css
    highlight-style: atom-one # espresso   tango
    mainfont:  sans-serif; serif; ui-sans-serif  # Gill Sans, sans-serif;
    toc: true
    include-after-body: target_blank.html
