project:
  type: website
  output-dir: "."
  
website:
  title: B.H. CHOE
  reader-mode: false
  navbar:
    # background: light
    # logo: img/logo-title-slide.png
    pinned: true
    left:
      - text: About
        href: cv.qmd
        
      - text: DANL 200 - Lecture
        menu:
        - text: 11 - facets, geoms
          href: lec/danl-200-lec-11-2023-0922.html
        - text: 10 - aesthetic mapping, facets, geoms
          href: lec/danl-200-lec-10-2023-0920.html
        - text: 09 - aesthetic mapping
          href: lec/danl-200-lec-09-2023-0918.html
        - text: 08 - data visualization
          href: lec/danl-200-lec-08-2023-0915.html
        - text: 07 - basics in r; data visualization
          href: lec/danl-200-lec-07-2023-0913.html
        - text: 06 - basics in r
          href: lec/danl-200-lec-06-2023-0911.html
        - text: 05 - basics in r
          href: lec/danl-200-lec-05-2023-0908.html
        - text: 04 - basics in r
          href: lec/danl-200-lec-04-2023-0906.html
        - text: 03 - basics in r
          href: lec/danl-200-lec-03-2023-0901.html
        - text: 02 - r; rstudio; tidyverse
          href: lec/danl-200-lec-02-2023-0830.html
        - text: 01 - syllabus
          href: lec/danl-200-lec-01-2023-0828.html
          
      - text: DANL 399 - Lecture
        menu:
        - text: 03 - data visualization
          href: lec/danl-399-lec-03-2023-0918.html
        - text: 02 - installing the tools; quarto; data viz
          href: lec/danl-399-lec-02-2023-0911.html
        - text: 01 - syllabus; installing the tools
          href: lec/danl-399-lec-01-2023-0906.html

      - text: ECON 340 - Lecture
        menu:
        - text: 11 - hw 1 review
          href: ex/econ340-hw-1.qmd
        - text: 10 - marginal analysis
          href: lec/econ-340-lec-10-2023-0920.html
        - text: 09 - pareto efficiency
          href: lec/econ-340-lec-09-2023-0918.html
        - text: 08 - open access problems; public goods problems
          href: lec/econ-340-lec-08-2023-0915.html
        - text: 07 - open access problems; public goods problems
          href: lec/econ-340-lec-07-2023-0913.html
        - text: 06 - externalities
          href: lec/econ-340-lec-06-2023-0911.html
        - text: 05 - social welfare; externalities
          href: lec/econ-340-lec-05-2023-0908.html
        - text: 04 - social welfare; externalities
          href: lec/econ-340-lec-04-2023-0906.html
        - text: 03 - social welfare
          href: lec/econ-340-lec-03-2023-0901.html
        - text: 02 - climate change; social welfare
          href: lec/econ-340-lec-02-2023-0830.html
        - text: 01 - syllabus
          href: lec/econ-340-lec-01-2023-0828.html

        
  sidebar:
    title: <b>Exercises</b>
    style: "docked"
    search: true
    background: dark
    foreground: light
    collapse-level: 1
    pinned: true
    border: true
    # type: light
    contents:
      - section: <font size ="6">Classwork</font>
      - text: "---"
      - section: <font size ="4">Data Analytics 200&ensp;&ensp; </font>
        contents:
        - text: 03 - ggplot - geometric objects
          href: ex/danl200-cw-3.qmd
        - text: 02 - ggplot - first step, aethetic mapping, facets
          href: ex/danl200-cw-2.qmd
        - text: 01 - Working with data.frame
          href: ex/danl200-cw-1.qmd
      - text: "---"
      - section: <font size ="4">Data Analytics 399&ensp;&ensp;</font>
        contents:
      - text: "---"
      - section: <font size ="4">Economics 340&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;</font>
        contents:
        - text: 05 - Lagrangian method
          href: ex/econ340-cw-5.qmd
        - text: 04 - Market equilibrium, social planner, and government
          href: ex/econ340-cw-4.qmd
        - text: 03 - Public goods game
          href: ex/econ340-cw-3.qmd
        - text: 02 - Utilty maximization
          href: ex/econ340-cw-2.qmd
        - text: 01 - Social welfare and landfills
          href: ex/econ340-cw-1.qmd
          
      - section: <font size ="6"> &nbsp; </font>
      
      - section: <font size ="6">Homework</font>
      - text: "---"
      - section: <font size ="4">Data Analytics 200&ensp;&ensp;</font>
        contents:
        - text: 01 - R basics; data visualization
          href: ex/danl200-hw-1.qmd
      - text: "---"
      - section: <font size ="4">Data Analytics 399&ensp;&ensp;</font>
        contents:
      - text: "---"
      - section: <font size ="4">Economics 340&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;</font>
        contents:
        - text: 01 - Negative externalities; the tradegy of the commons
          href: ex/econ340-hw-1.qmd
  
  page-footer: 
    center: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2023"
    # foreground: dark
    # background: '#9b4e55'
    
format:
  html: 
    theme:
      light: [yeti]
      dark: [solar, theme-dark.scss]
    css: styles.css
    # highlight-style: atom-one
    highlight-style: espresso
    mainfont:  sans-serif; serif; ui-sans-serif
    # mainfont: Gill Sans, sans-serif;
    toc: true
    include-after-body: target_blank.html
