project: 
  type: website 
  output-dir: "."
  
website:
  title: "B.H. CHOE&nbsp;&nbsp;&nbsp;"
  favicon: img/favicon.ico
  description: 'A collection of data analytics course contents by Byeong-Hak Choe'
  reader-mode: false
  back-to-top-navigation: true

  navbar:
    background: "#1c4982"
    logo: img/geneseo-logo-squared.png
    pinned: true

  sidebar:
    title: "Welcome!"
    style: docked
    search: false
    collapse-level: 0
    pinned: true
    border: true
    # type: light
    contents:
      - section: |
          <a href="./index.html"><font size ="5" ><b>Welcome! </b></font><font size ="5" color="#194493"><i class="fa fa-user-circle" aria-hidden="true"></i> <i class="fa fa-sun" aria-hidden="true"></i></font></a>

      - section: <font size ="2">&ensp;&ensp; </font>

      - section: |
          <font size ="5" ><b>DANL 200 </b></font><font size ="5" color="#194493"><i class="fa fa-step-forward" aria-hidden="true"></i></font>
        contents:
        - text: <font size ="5" >Lecture </font><font size ="5" color="#194493">{{< fa solid laptop >}}</font>
          href: listing-danl-lec-200.qmd
        - text: <font size ="5" >Q & A </font><font size ="5" color="#194493">{{< fa solid commenting >}}</font>
          href: listing-danl-qa-200.qmd
        - text: <font size ="5" >Classwork </font><font size ="5" color="#194493">{{< fa solid keyboard >}}</font>
          href: listing-danl-cw-200.qmd
        - text: <font size ="5" >Homework </font><font size ="5" color="#194493">{{< fa solid level-up >}}</font>
          href: listing-danl-hw-200.qmd

      - section: <font size ="2">&ensp;&ensp; </font>
      
      - section: |
          <font size ="5" ><b>DANL 210 </b></font><font size ="5" color="#194493"><i class="fa fa-step-forward" aria-hidden="true"></i></font>
        contents:
        - text: <font size ="5" >Lecture </font><font size ="5" color="#194493">{{< fa solid laptop >}}</font>
          href: listing-danl-lec-210.qmd
        - text: <font size ="5" >Q & A </font><font size ="5" color="#194493">{{< fa solid commenting >}}</font>
          href: listing-danl-qa-210.qmd
        - text: <font size ="5" >Classwork </font><font size ="5" color="#194493">{{< fa solid keyboard >}}</font>
          href: listing-danl-cw-210.qmd
        - text: <font size ="5" >Homework </font><font size ="5" color="#194493">{{< fa solid level-up >}}</font>
          href: listing-danl-hw-210.qmd

  page-footer: 
    center: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2024"
    # foreground: dark
    # background: '#9b4e55' 
    
format:
  html: 
    grid:
      margin-width: 400px
      sidebar-width: 275px
    link-external-newwindow: true
    theme:
      light: [flatly]  # flatly litera sandstone 'assets/scss/light.scss'
      dark: [darkly, theme-dark.scss] # darkly cyborg slate solra superhero
    css: [styles.css, assets/css/font.css] # , font.css
    highlight-style: atom-one # espresso   tango
    mainfont:  sans-serif; serif; ui-sans-serif  # Gill Sans, sans-serif;
    toc: true
    # include-after-body: [target-blank.html]
