project: 
  type: website
  output-dir: "."
  
website:
  title: "&nbsp;B.H. CHOE"
  favicon: img/favicon.ico
  description: 'A collection of data analytics course contents by Byeong-Hak Choe'
  reader-mode: false
  back-to-top-navigation: true
  
  navbar:
    background: "#194493"  # "#003896"
    # foreground: "#0149ab"
    
    logo: img/geneseo-logo-square.png
    pinned: true
    left:
      - text: "DANL200: Lecture"
        url: https://bcdanl.github.io/danl-200-listing-lec.html
        
      - text: Classwork
        url: https://bcdanl.github.io/danl-200-listing-cw.html
        
      - text: Homework
        url: https://bcdanl.github.io/danl-200-listing-hw.html
        
      - text: Project
        url: https://bcdanl.github.io
        
      - text: Exam
        url: https://bcdanl.github.io
        

      - text: " "
      - text: "||"
        url: https://bcdanl.github.io
      - text: " "
      
      - text: "DANL210: Lecture"
        url: https://bcdanl.github.io/danl-210-listing-lec.html
        
      - text: Classwork
        url: https://bcdanl.github.io/danl-210-listing-cw.html
        
      - text: Homework
        url: danl-210-listing-hw.qmd
        
      - text: Project
        url: https://bcdanl.github.io
        
      - text: Exam
        url: https://bcdanl.github.io
        

      
    # right:
    #   - text: About
    #     href: cv/cv.qmd

        

  page-footer: 
    center: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2024"
    # foreground: dark
    # background: '#9b4e55' 
    
format:
  html: 
    theme:
      light: [flatly]  # flatly litera sandstone 'assets/scss/light.scss'
      dark: [darkly, theme-dark.scss] # darkly cyborg slate solra superhero
    css: [styles.css, assets/css/font.css] # , font.css
    highlight-style: atom-one # espresso   tango
    mainfont:  sans-serif; serif; ui-sans-serif  # Gill Sans, sans-serif;
    toc: true
    # include-after-body: [target_blank.html, target_blank2.html]
