project:
  type: website
  output-dir: "."
  
website:
  title: "B.H. CHOE"
  page-footer: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2023"
  reader-mode: false
  navbar:
    pinned: true
    left:
      - text: about
        href: cv.qmd
      - text: danl200-lec
        menu:
        - text: "lecture 25 - linear regression with interaction terms"
          href: DANL200_Lec25_20230509.html
        - text: "lecture 24 - linear regression with interaction terms"
          href: DANL200_Lec24_20230504.html
        - text: "lecture 23 - linear regression with log transformation"
          href: DANL200_Lec23_20230502.html
        - text: "lecture 22 - linear regression"
          href: DANL200_Lec22_20230427.html
        - text: "lecture 21 - linear regression"
          href: DANL200_Lec21_20230425.html
        - text: "lecture 20 - linear regression"
          href: DANL200_Lec20_20230420.html
        - text: "lecture 19 - strings, dates and times, linear regression"
          href: DANL200_Lec19_20230418.html
        - text: "lecture 18 - factor, strings, dates and times"
          href: DANL200_Lec18_20230413.html
        - text: "lecture 17 - tidy data, joins"
          href: DANL200_Lec17_20230411.html
        - text: "lecture 16 - tidy data - pivot, separate, unite"
          href: DANL200_Lec16_20230406.html
        - text: "lecture 15 - log transformation, summarize, group operation"
          href: DANL200_Lec15_20230323.html
        - text: "lecture 14 - summarize, group operation"
          href: DANL200_Lec14_20230321.html
        - text: "lecture 13 - select, mutate"
          href: DANL200_Lec13_20230309.html
        - text: "lecture 12 - filter, arrange, select"
          href: DANL200_Lec12_20230307.html
        - text: "lecture 11 - visualization, filter"
          href: DANL200_Lec11_20230302.html
        - text: "lecture 10 - visualization"
          href: DANL200_Lec10_20230223.html
        - text: "lecture 09 - ggplot, visualization"
          href: DANL200_Lec09_20230221.html
        - text: "lecture 08 - ggplot"
          href: DANL200_Lec08_20230216.html
        - text: "lecture 07 - ggplot"
          href: DANL200_Lec07_20230214.html
        - text: "lecture 06 - ggplot"
          href: DANL200_Lec06_20230209.html
        - text: "lecture 05 - ggplot"
          href: DANL200_Lec05_20230207.html
        - text: "lecture 04 - ggplot"
          href: DANL200_Lec04_20230202.html
        - text: "lecture 03 - r basic, ggplot"
          href: DANL200_Lec03_20230131.html
        - text: "lecture 02 - r basic"
          href: DANL200_Lec02_20230126.html
        - text: "lecture 01 - syllabus"
          href: DANL200_Lec01_20230124.html
      - text: danl200-lab
        menu:
        - text: final-exam-1-fall-2022-a
          href: DANL200_final_1a_fall_2022.qmd 
        - text: final-exam-2-fall-2022-a
          href: DANL200_final_2a_fall_2022.qmd 
        - text: final-exam-3-fall-2022-a
          href: DANL200_final_3a_fall_2022.qmd 
        - text: hw4-a
          href: DANL200_hw4a.qmd 
        # - text: hw4-q
        #   href: DANL200_hw4q.qmd  
        - text: hw3-a
          href: DANL200_hw3a.qmd  
        # - text: hw3-q
        #   href: DANL200_hw3q.qmd  
        - text: lab5-a
          href: DANL200_lab5a.qmd
        # - text: lab5-q
        #   href: DANL200_lab5q.qmd
        - text: lab4-a
          href: DANL200_lab4a.qmd
        # - text: lab4-q
        #   href: DANL200_lab4q.qmd
        - text: lab3-a
          href: DANL200_lab3a.qmd
        # - text: lab3-q
        #   href: DANL200_lab3q.qmd
        - text: midterm-spring-2023-a
          href: DANL200_midterm-spring-2023-a.qmd
        # - text: midterm-spring-2023-q
        #   href: DANL200_midterm-spring-2023-q.qmd
        - text: midterm-fall-2022-a
          href: DANL200_midterm-fall-2022-a.qmd
        # - text: midterm-fall-2022-q
        #   href: DANL200_midterm-fall-2022-q.qmd
        - text: midterm-spring-2022-a
          href: DANL200_midterm-spring-2022-a.qmd
        # - text: midterm-spring-2022-q
        #   href: DANL200_midterm-spring-2022-q.qmd
        - text: lab2-a
          href: DANL200_lab2a.qmd
        # - text: lab2-q
        #   href: DANL200_lab2q.qmd
        - text: hw2-a
          href: DANL200_hw2a.qmd  
        # - text: hw2-q
        #   href: DANL200_hw2q.qmd  
        - text: lab1-a
          href: DANL200_lab1a.qmd
        # - text: lab1-q
        #   href: DANL200_lab1q.qmd
        - text: hw1-a
          href: DANL200_hw1a.qmd
        # - text: hw1-q
        #   href: DANL200_hw1q.qmd
          
      - text: danl210-lec
        menu:
        - text: "lecture 25 - unofficial api"
          href: DANL210_Lec25_20230509.html
        - text: "lecture 24 - api"
          href: DANL210_Lec24_20230504.html
        - text: "lecture 23 - web scrapping"
          href: DANL210_Lec23_20230502.html
        - text: "lecture 22 - web scrapping"
          href: DANL210_Lec22_20230427.html
        - text: "lecture 21 - web scrapping"
          href: DANL210_Lec21_20230425.html
        - text: "lecture 20 - web scrapping"
          href: DANL210_Lec20_20230420.html
        - text: "lecture 19 - web scrapping"
          href: DANL210_Lec19_20230418.html
        - text: "lecture 18 - missing data, dates and times"
          href: DANL210_Lec18_20230413.html
        - text: "lecture 17 - data concatenation, merges, missing data"
          href: DANL210_Lec17_20230411.html
        - text: "lecture 16 - data types, data concatenation, merges"
          href: DANL210_Lec16_20230406.html
        - text: "lecture 15 - tidy, data types"
          href: DANL210_Lec15_20230323.html
        - text: "lecture 14 - agg, transform, filter, tidy"
          href: DANL210_Lec14_20230321.html
        - text: "lecture 13 - agg, transform, filter"
          href: DANL210_Lec13_20230309.html
        - text: "lecture 12 - seaborn, agg"
          href: DANL210_Lec12_20230307.html
        - text: "lecture 11 - seaborn"
          href: DANL210_Lec11_20230302.html
        - text: "lecture 10 - eda"
          href: DANL210_Lec10_20230223.html
        - text: "lecture 09 - apply"
          href: DANL210_Lec09_20230221.html
        - text: "lecture 08 - query, drop, sort, rank, assign, lambda"
          href: DANL210_Lec08_20230216.html
        - text: "lecture 07 - drop, sort, rank, assign, lambda"
          href: DANL210_Lec07_20230214.html
        - text: "lecture 06 - pandas boolean subsetting"
          href: DANL210_Lec06_20230209.html
        - text: "lecture 05 - pandas loc iloc"
          href: DANL210_Lec05_20230207.html
        - text: "lecture 04 - python basic, pandas"
          href: DANL210_Lec04_20230202.html
        - text: "lecture 03 - python basic"
          href: DANL210_Lec03_20230131.html
        - text: "lecture 02 - python basic"
          href: DANL210_Lec02_20230126.html
        - text: "lecture 01 - syllabus"
          href: DANL210_Lec01_20230124.html
      - text: danl210-lab
        menu: 
        - text: "hw5-q - Automation - World Bank Climate Change Knowledge"
          href: DANL210_hw5q.qmd
        - text: "hw4-a - Web-scrapping - Books"
          href: DANL210_hw4a.qmd
        # - text: "hw4-q - Web-scrapping - Books"
        #   href: DANL210_hw4q.qmd
        - text: "hw3-a - Web-scrapping - IMDB"
          href: DANL210_hw3a.qmd
        # - text: hw3-q
        #   href: DANL210_hw3q.qmd
        - text: "lab8-a - Web-scrapping 3 - Quotes"
          href: DANL210_lab8a.qmd
        # - text: lab8-q
        #   href: DANL210_lab8q.qmd
        - text: "lab7-a - Web-scrapping 2 - EIA"
          href: DANL210_lab7a.qmd
        # - text: lab7-q
        #   href: DANL210_lab7q.qmd
        - text: "lab6-a - Web-scrapping 1 - HTML Table"
          href: DANL210_lab6a.qmd
        # - text: lab6-q
        #   href: DANL210_lab6q.qmd
        - text: "lab5-a - datetime"
          href: DANL210_lab5a.qmd
        # - text: lab5-q
        #   href: DANL210_lab5q.qmd
        - text: "lab4-a - concat, merge"
          href: DANL210_lab4a.qmd
        # - text: lab4-q
        #   href: DANL210_lab4q.qmd
        - text: midterm-spring-2023-a
          href: DANL210_midterm-spring-2023-a.qmd  
        # - text: midterm-spring-2023-q
        #   href: DANL210_midterm-spring-2023-q.qmd 
        - text: "lab3-a - melt, pivot"
          href: DANL210_lab3a.qmd    
        # - text: lab3-q
        #   href: DANL210_lab3q.qmd   
        - text: "hw2-a - pandas"
          href: DANL210_hw2a.qmd  
        # - text: hw2-q
        #   href: DANL210_hw2q.qmd
        - text: "lab2-a - pandas, seaborn"
          href: DANL210_lab2a.qmd  
        # - text: lab2-q
        #   href: DANL210_lab2q.qmd  
        # - text: lab1-q
        #   href: DANL210_lab1q_v3.qmd
        - text: "lab1-a - pandas"
          href: DANL210_lab1a.qmd 
        - text: "hw1-a - pandas"
          href: DANL210_hw1a.qmd 
        # - text: hw1-q
        #   href: DANL210_hw1q.qmd    
          
      - text: danl310-lec
        menu:
        - text: "lecture 24 - quarto"
          href: DANL310_Lec24_20230504.html
        - text: "lecture 23 - data viz"
          href: DANL310_Lec23_20230502.html
        - text: "lecture 22 - shiny apps"
          href: DANL310_shiny_workshop.pdf
        - text: "lecture 21 - shiny apps"
          href: DANL310_shiny_workshop.pdf
        - text: "lecture 20 - shiny apps"
          href: DANL310_shiny_workshop.pdf
        - text: "lecture 19 - tables"
          href: DANL310_Lec19_20230418.html
        - text: "lecture 18 - animation ggplot"
          href: DANL310_Lec18_20230413.html
        - text: "lecture 17 - interactive ggplot"
          href: DANL310_Lec17_20230411.html
        - text: "lecture 15 - maps"
          href: DANL310_Lec15_20230323.html
        - text: "lecture 14 - maps"
          href: DANL310_Lec14_20230321.html
        - text: "lecture 13 - color, theme"
          href: DANL310_Lec13_20230309.html
        - text: "lecture 12 - work with model"
          href: DANL310_Lec12_20230307.html
        - text: "lecture 11 - ggplot"
          href: DANL310_Lec11_20230302.html
        - text: "lecture 10 - ggplot"
          href: DANL310_Lec10_20230223.html
        - text: "lecture 09 - ggplot"
          href: DANL310_Lec09_20230221.html
        - text: "lecture 08 - ggplot"
          href: DANL310_Lec08_20230216.html
        - text: "lecture 07 - ggplot"
          href: DANL310_Lec07_20230214.html
        - text: "lecture 06 - ggplot"
          href: DANL310_Lec06_20230209.html
        - text: "lecture 05 - ggplot"
          href: DANL310_Lec05_20230207.html
        - text: "lecture 04 - ggplot"
          href: DANL310_Lec04_20230202.html
        - text: "lecture 03 - rmarkdown"
          href: DANL310_Lec03_20230131.html
        - text: "lecture 02 - github website, rmarkdown"
          href: DANL310_Lec02_20230126.html
        - text: "lecture 01 - syllabus"
          href: DANL310_Lec01_20230124.html
      - text: danl310-lab
        menu:
        - text: lab4-q
          href: DANL310_lab4q.qmd
        - text: "shiny-04: interactive storm map"
          href: shiny-04.qmd 
        - text: "shiny-03: storms filtered"
          href: shiny-03.qmd 
        - text: "shiny-02: storms by year"
          href: shiny-02.qmd 
        - text: "shiny-01: old faithful"
          href: shiny-01.qmd 
        - text: "Large-File-Push to GitHub Repo"
          href: git-large-file-push.qmd 
        - text: midterm-spring-2023-a
          href: DANL310_midterm-spring-2023-a.qmd 
        - text: midterm-spring-2023-q
          href: DANL310_midterm-spring-2023-q.qmd 
        - text: lab3-a
          href: DANL310_lab3a.qmd
        - text: lab3-q
          href: DANL310_lab3q.qmd
        - text: lab2-a
          href: DANL310_lab2a.qmd
        - text: lab2-q
          href: DANL310_lab2q.qmd
        - text: lab1-a
          href: DANL310_lab1a.qmd
        - text: lab1-q
          href: DANL310_lab1q.qmd
        - text: hw2-a
          href: DANL310_hw2a.qmd
        - text: hw2-q
          href: DANL310_hw2q.qmd
        - text: hw1-a
          href: DANL310_hw1a.qmd
        - text: hw1-q
          href: DANL310_hw1q.qmd
      - text: ml-lab
        menu:
        - text: linear regression
          href: mba-ch1-lm.qmd
        - text: logistic regression (classification)
          href: mba-ch1-logit.qmd
        - text: regularization
          href: mba-ch3-regularization.qmd
        - text: "model selection"
          href: mba-ch3-model-selection.html
        - text: "tree-based methods"
          href: mba-ch7-tree-based-methods.qmd
        # - text: "classification"
        #   # href: mba-ch1-lm.qmd
        - text: "clustering"
          # href: mba-ch1-lm.qmd
        - text: "principal component analysis"
          # href: mba-ch1-lm.qmd
        # - text: "double ml"
          # href: mba-ch1-lm.qmd
format:
  html:
    theme:
      light: [flatly]
      dark: [darkly, theme-dark.scss]
    css: styles.css
    # mainfont: Georgia, serif;
    mainfont: Gill Sans, sans-serif;
    toc: true
    include-after-body: target_blank.html
