project:
  type: website
  output-dir: "."
  
website:
  title: B.H. CHOE
  reader-mode: false
  navbar:
    # background: light
    # logo: img/logo-title-slide.png
    pinned: true
    left:
      - text: About
        href: cv.qmd
        
      - text: DANL 200 - Lecture
        menu:
        - text: 06 - basics in r
          href: lec/danl-200-lec-06-2023-0911.html
        - text: 05 - basics in r
          href: lec/danl-200-lec-05-2023-0908.html
        - text: 04 - basics in r
          href: lec/danl-200-lec-04-2023-0906.html
        - text: 03 - basics in r
          href: lec/danl-200-lec-03-2023-0901.html
        - text: 02 - r; rstudio; tidyverse
          href: lec/danl-200-lec-02-2023-0830.html
        - text: 01 - syllabus
          href: lec/danl-200-lec-01-2023-0828.html
          
      - text: DANL 399 - Lecture
        menu:
        - text: 02 - installing the tools; quarto; data viz
          href: lec/danl-399-lec-02-2023-0911.html
        - text: 01 - syllabus; installing the tools
          href: lec/danl-399-lec-01-2023-0906.html

      - text: ECON 340 - Lecture
        menu:
        - text: 06 - externalities
          href: lec/econ-340-lec-06-2023-0911.html
        - text: 05 - social welfare; externalities
          href: lec/econ-340-lec-05-2023-0908.html
        - text: 04 - social welfare; externalities
          href: lec/econ-340-lec-04-2023-0906.html
        - text: 03 - social welfare
          href: lec/econ-340-lec-03-2023-0901.html
        - text: 02 - climate change; social welfare
          href: lec/econ-340-lec-02-2023-0830.html
        - text: 01 - syllabus
          href: lec/econ-340-lec-01-2023-0828.html

        
  sidebar:
    title: <b>Exercises</b>
    style: "docked"
    search: true
    background: dark
    foreground: light
    collapse-level: 1
    pinned: true
    border: true
    # type: light
    contents:
      - section: <font size ="6">Classwork</font>
      - text: "---"
      - section: <font size ="4">Data Analytics 200</font>
        contents:
        - text: 02 - Data visualization with ggplot
          href: ex/danl200-cw-2.qmd
        - text: 01 - Working with data.frame
          href: ex/danl200-cw-1.qmd
      - text: "---"
      - section: <font size ="4">Data Analytics 399</font>
        contents:
      - text: "---"
      - section: <font size ="4">Economics 340</font>
        contents:
        - text: 02 - Utilty maximization
          href: ex/econ340-cw-2.qmd
        - text: 01 - Social welfare and landfills
          href: ex/econ340-cw-1.qmd
          
      - section: <font size ="6"> &nbsp; </font>
      
      - section: <font size ="6">Homework</font>
      - text: "---"
      - section: <font size ="4">Data Analytics 200</font>
        contents:
        - text: 01 - R basics; data visualization
          href: ex/danl200-hw-1.qmd
      - text: "---"
      - section: <font size ="4">Data Analytics 399</font>
        contents:
      - text: "---"
      - section: <font size ="4">Economics 340</font>
        contents:
        - text: 01 - Negative externalities; the tradegy of the commons
          href: ex/econ340-hw-1.qmd
  
  page-footer: 
    center: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2023"
    # foreground: dark
    # background: '#9b4e55'
    
format:
  html:
    theme:
      light: [yeti]
      dark: [solar, theme-dark.scss]
    css: styles.css
    highlight-style: atom-one
    mainfont:  sans-serif; serif; ui-sans-serif
    # mainfont: Gill Sans, sans-serif;
    toc: true
    include-after-body: target_blank.html
