project:
  type: website
  output-dir: "."
  
website:
  title: B.H. CHOE
  reader-mode: false
  navbar:
    # background: light
    # logo: img/logo-title-slide.png
    pinned: true
    left:
      - text: About
        href: cv.qmd
        
      - text: DANL 200 - Lecture
        menu:
        - text: 05 - basics in r
          href: lec/danl-200-lec-05-2023-0908.html
        - text: 04 - basics in r
          href: lec/danl-200-lec-04-2023-0906.html
        - text: 03 - basics in r
          href: lec/danl-200-lec-03-2023-0901.html
        - text: 02 - r, rstudio, tidyverse
          href: lec/danl-200-lec-02-2023-0830.html
        - text: 01 - syllabus
          href: lec/danl-200-lec-01-2023-0828.html
          
      # - text: danl200-ex
      #   menu:
      #   - text: ex 2 - data visualization with ggplot
      #     href: exercises/danl200-class-exercise-2.qmd
      #   - text: ex 1 - working with data.frame
      #     href: exercises/danl200-class-exercise-1.qmd
          
      - text: ECON 340 - Lecture
        menu:
        - text: 05 - social welfare, externalities
          href: lec/econ-340-lec-05-2023-0908.html
        - text: 04 - social welfare, externalities
          href: lec/econ-340-lec-04-2023-0906.html
        - text: 03 - social welfare
          href: lec/econ-340-lec-03-2023-0901.html
        - text: 02 - climate change, social welfare
          href: lec/econ-340-lec-02-2023-0830.html
        - text: 01 - syllabus
          href: lec/econ-340-lec-01-2023-0828.html
          
      # - text: econ340-ex
      #   menu:
      #   - text: ex 1 - social welfare and landfills
      #     href: exercises/econ340-class-exercise-1.qmd
        
      - text: DANL 399 - Lecture
        menu:
        - text: 01 - syllabus, installing the tools
          href: lec/danl-399-lec-01-2023-0906.html
  sidebar:
    title: <b>Exercises</b>
    style: "docked"
    search: true
    background: dark
    foreground: light
    collapse-level: 1
    pinned: true
    border: true
    # type: light
    contents:
      - section: <font size ="5">Exercises</font>
      - text: "---"
      - section: <font size ="4">ECON 340</font>
        contents:
        - text: 01 - Social welfare and landfills
          href: exercises/econ340-class-exercise-1.qmd
      - text: "---"
      - section: <font size ="4">DANL 200</font>
        contents:
        - text: 02 - Data visualization with ggplot
          href: exercises/danl200-class-exercise-2.qmd
        - text: 01 - Working with data.frame
          href: exercises/danl200-class-exercise-1.qmd
      - text: "---"
      - section: <font size ="4">DANL 399</font>
        contents:
  
  page-footer: 
    center: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2023"
    foreground: dark
    background: '#9b4e55'
    
format:
  html:
    theme:
      light: [yeti]
      dark: [solar, theme-dark.scss]
    css: styles.css
    mainfont:  sans-serif; serif; ui-sans-serif
    # mainfont: Gill Sans, sans-serif;
    toc: true
    include-after-body: target_blank.html
