project:
  type: website
  output-dir: "."
  
website:
  title: "B.H. CHOE"
  page-footer: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2023"
  reader-mode: false
  navbar:
    pinned: true
    left:
      - text: about
        href: cv.qmd
        
      - text: danl200-lec
        menu:
        - text: lecture 05 - basics in r
          href: lec/danl-200-lec-05-2023-0908.html
        - text: lecture 04 - basics in r
          href: lec/danl-200-lec-04-2023-0906.html
        - text: lecture 03 - basics in r
          href: lec/danl-200-lec-03-2023-0901.html
        - text: lecture 02 - r, rstudio, tidyverse
          href: lec/danl-200-lec-02-2023-0830.html
        - text: lecture 01 - syllabus
          href: lec/danl-200-lec-01-2023-0828.html
          
      - text: danl200-ex
        menu:
        - text: ex 2 - data visualization with ggplot
          href: exercises/danl200-class-exercise-2.qmd
        - text: ex 1 - working with data.frame
          href: exercises/danl200-class-exercise-1.qmd
          
      - text: econ340-lec
        menu:
        - text: lecture 05 - social welfare, externalities
          href: lec/econ-340-lec-05-2023-0908.html
        - text: lecture 04 - social welfare, externalities
          href: lec/econ-340-lec-04-2023-0906.html
        - text: lecture 03 - social welfare
          href: lec/econ-340-lec-03-2023-0901.html
        - text: lecture 02 - climate change, social welfare
          href: lec/econ-340-lec-02-2023-0830.html
        - text: lecture 01 - syllabus
          href: lec/econ-340-lec-01-2023-0828.html
          
      - text: econ340-ex
        menu:
        - text: ex 1 - social welfare and landfills
          href: exercises/econ340-class-exercise-1.qmd
        
      - text: danl399-lec
        menu:
        - text: lecture 01 - syllabus, installing the tools
          href: lec/danl-399-lec-01-2023-0906.html
          
format:
  html:
    theme:
      light: [united]
      dark: [vapor, theme-dark.scss]
    css: styles.css
    # mainfont: Georgia, serif;
    mainfont: Gill Sans, sans-serif;
    toc: true
    include-after-body: target_blank.html
