project: 
  type: website
  output-dir: "." 
  
website:
  title: "&nbsp;B.H. CHOE&nbsp;&nbsp;&nbsp;"
  favicon: img/favicon.ico
  description: 'A collection of data analytics course contents by Byeong-Hak Choe'
  reader-mode: false
  back-to-top-navigation: true
  
  navbar:
    background: "#194493"  # "#003896"
    # foreground: "#0149ab"
    
    logo: img/geneseo-logo-square.png
    pinned: true
    right:
      - text: DANL 200
        menu: 
        - text: Lecture Q & A
          href: listing-danl-qa-200.qmd
        - text: Classwork
          href: listing-danl-cw-200.qmd
        - text: Homework
          href: listing-danl-hw-200.qmd
        - text: Project
        - text: Exam
      - text: DANL 210
        menu: 
        - text: Lecture Q & A
          href: listing-danl-qa-210.qmd
        - text: Classwork
          href: listing-danl-cw-210.qmd
        - text: Homework
          href: listing-danl-hw-210.qmd
        - text: Project
        - text: Exam
        
    # right:
    #   - text: About
    #     href: cv/cv.qmd

        

  page-footer: 
    center: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2024"
    # foreground: dark
    # background: '#9b4e55' 
    
format:
  html: 
    link-external-newwindow: true
    theme:
      light: [flatly]  # flatly litera sandstone 'assets/scss/light.scss'
      dark: [darkly, theme-dark.scss] # darkly cyborg slate solra superhero
    css: [styles.css, assets/css/font.css] # , font.css
    highlight-style: atom-one # espresso   tango
    mainfont:  sans-serif; serif; ui-sans-serif  # Gill Sans, sans-serif;
    toc: true
    # include-after-body: [target_blank.html]
