---
title: "DANL 100: Programming for Data Analytics"
subtitle: "DANL 100 - Homework Assignment 1<br><br>" 
author: 
  - "Byeong-Hak Choe<br>"
date: "`r Sys.Date()`<br><br>"
output: 
  html_document:
    df_print: paged
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: false
    highlight: espresso
---
```{r klippy, echo=FALSE, include=TRUE}
htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa fa-clipboard\"></i>",
    success_text = "<i class=\"fa fa-check\" style=\"color: #90BE6D\"></i>",
  ),
  rmarkdown::html_dependency_font_awesome()
)

```

# Question 1

```{python, eval = F, echo = T}
list_variable = [100, 144, 169, 1000, 8]
```


Write a Python code that uses `print()` and `max()` functions to print out the largest value in the list, `list_variable`, as follows:

<div style="font-family:courier">The largest value in the list is: 1000</div>
<div style="font-family:courier">The smallest value in the list is: 8</div>



```{python}
# Answer
list_variable = [100, 144, 169, 1000, 8]

print('The largest value in the list is:', max(list_variable),',\n'
      'The smallest value in the list is:', min(list_variable), '.')
```


<br><br><br> 

# Question 2

```{python, eval = F, echo = T}
fare = "$10.00"
tip = "2.00$"
tax = "$ 0.80"
```


Write a Python code that uses *slicing* and the `print()` function to print out the following message: 

<div style="font-family:courier">The total trip cost is: $12.80</div>



```{python}
# Answer
fare = "$10.00"
tip = "2.00$"
tax = "$ 0.80"

fare = fare[1:]
tip = tip[0:3]
tax = tax[2:]

# add up float values and assign to trip_total variable
trip_total = float(fare) + float(tip) + float(tax)
print ("The total trip cost is:", "$" + str(trip_total))
```

    
<br><br><br>

# Question 3

```{python, eval = F, echo = T}
x = 4.0
y = .5
```


For each expression below, what is the value of the expression? Explain thoroughly.

```{python, eval = F, echo = T}
20 == '20'
bool(0) != bool('')
x < y or 3*y < x
not (100 == '100' and 25 < 36)
```

a. The statement `20 == '20'` is `False`.
  - The left-hand side `20` is integer and the right-hand side `'20'` is string.
  
<br>

b. The statement `bool(0) != bool('')` is `False`.
  - The left-hand side `bool(0)` is `False`.
  - The right-hand side `bool('')` is `False`.
  - The statement `False != False` is `False`.
  
<br>

c. The statement `x < y or 3*y < x` is `True`.
  - Let `x < y` be the statement A. The statement A is `False`.
  - Let `3*y < x` be the statement B. The statement B is `True`.
  - The statement `A or B` is `True`, because either `A` or `B` is `True`.
  
<br>

d. The statement `not (100 == '100' and 25 < 36)` is `True`.
  - Let `100 == '100'` be the statement C. 
  - The statement C is `False`, because the left-hand side 100 is integer and the right-hand side '100' is string.
  - Let `25 < 36` be the statement D. The statement D is `True`.
  - The statement `C and D` is `False`, because either `C` or `D` is `False`.
  - The statement `not (C and D)` is `True`, because `not (False)` is `not False`, which is `True`.

<br><br><br>

# Question 4

This Python code creates a tuple with seven different ages:

```{python, eval = F, echo = T}
respondent_ages = (65, 29, 25, 35, 58, 23, 19)
```

Write a Python code that uses a *for-loop* statement and a *if-else* statement to assign the list, `under40_list`, to `[29, 25, 35, 23, 19]` and the list, `over40_list`, to `[65, 58]`.

```{python}
# Answer
respondent_ages = (65, 29, 25, 35, 58, 23, 19)

under40_list = []
over40_list = []
for age in respondent_ages:
    if age < 40:
        under40_list.append(age)
    else:
        over40_list.append(age)
        
print(under40_list)
print(over40_list)
```

<br><br><br>

# Question 5

```{python, eval = F, echo = T}
tuple_var = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
total = 0
```

Write a Python code that uses the following two lines (1) a *for-loop* statement to process each element of `tuple_var` and (2) the following line.

```{python, eval = F, echo = T}
print("The total of the values in the tuple is: ", total)
```

```{python}
# Answer

tuple_var = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
total = 0
for value in tuple_var:   # tuple is iterable.
    total += value

print("The total of the values in the tuple is: ", total)
```

- When we have a list of things to loop through, we can construct a `for` loop.
  - The above for-loop is equivalent to the following Python code without for-loop.

```{python}
tuple_var = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
total = 0

total = total + tuple_var[0]
total = total + tuple_var[1]
total = total + tuple_var[2]
total = total + tuple_var[3]
total = total + tuple_var[4]
total = total + tuple_var[5]
total = total + tuple_var[6]
total = total + tuple_var[7]
total = total + tuple_var[8]
total = total + tuple_var[9]

print("The total of the values in the tuple is: ", total)
```

<br><br><br>
  
# Question 6

Write a Python code that uses a *while-loop* and the `print()` function to print out the following message 5 times:

<div style="font-family:courier">Programming for Data Analytics is so fun!</div>

```{python}
# Answer
i = 0
while i < 5:
    print("Programming for Data Analytics is so fun!")
    i += 1
```

- Step 1. We first assigned the value 0 to `i`.

- Step 2. The `while` loop compared the value of `i` to 5 and continued if `i` was less than 5.

- Step 3. Inside the `while` loop, we printed `Programming for Data Analytics is so fun!` and then incremented `i` by 1 with the statement `i += 1`.

- Step 4. Python goes back to the top of the loop, and again compares `i` with 5.

- Step 5. The value of `i` is now 1, so the contents of the `while` loop are again executed, and `i` is incremented to 2.

- Step 6. This continues until `i` is incremented from 4 to 5 at the bottom of the loop.

- Step 7. On the next trip to the top, `i < 5` is now `False`, and the `while` loop ends.
