---
title: "DANL 100: Programming for Data Analytics"
subtitle: "DANL 100 - Homework Assignment 1<br><br>" 
author: 
  - "Byeong-Hak Choe<br>"
date: "`r Sys.Date()`<br><br>"
output: 
  html_document:
    df_print: paged
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: false
    highlight: espresso
---
```{r klippy, echo=FALSE, include=TRUE}
htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa fa-clipboard\"></i>",
    success_text = "<i class=\"fa fa-check\" style=\"color: #90BE6D\"></i>",
  ),
  rmarkdown::html_dependency_font_awesome()
)

```

# Question 1

```{python, eval = F, echo = T}
list_variable = [100, 144, 169, 1000, 8]
```


Write a Python code that uses `print()` and `max()` functions to print out the largest value in the list, `list_variable`, as follows:

<div style="font-family:courier">The largest value in the list is: 1000</div>
<div style="font-family:courier">The smallest value in the list is: 8</div>

<br><br><br> 

# Question 2

```{python, eval = F, echo = T}
fare = "$10.00"
tip = "2.00$"
tax = "$ 0.80"
```


Write a Python code that uses *slicing* and the `print()` function to print out the following message: 

<div style="font-family:courier">The total trip cost is: $12.80</div>

    
<br><br><br>

# Question 3

```{python, eval = F, echo = T}
x = 4.0
y = .5
```


For each expression below, what is the value of the expression? Explain thoroughly.

```{python, eval = F, echo = T}
20 == '20'
bool(0) != bool('')
x < y or 3*y < x
not (100 == '100' and 25 < 36)
```



<br><br><br>

# Question 4

This Python code creates a tuple with seven different ages:

```{python, eval = F, echo = T}
respondent_ages = (65, 29, 25, 35, 58, 23, 19)
```

Write a Python code that uses a *for-loop* statement and a *if-else* statement to assign the list, `under40_list`, to `[29, 25, 35, 23, 19]` and the list, `over40_list`, to `[65, 58]`.


<br><br><br>

# Question 5

```{python, eval = F, echo = T}
tuple_var = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
total = 0
```

Write a Python code that uses the following two lines (1) a *for-loop* statement to process each element of `tuple_var` and (2) the following line.

```{python, eval = F, echo = T}
print("The total of the values in the tuple is: ", total)
```
    

<br><br><br>
  
# Question 6

Write a Python code that uses a *while-loop* and the `print()` function to print out the following message 5 times:

<div style="font-family:courier">Programming for Data Analytics is so fun!</div>
