---
title: "Python Lab 5 - Dates and Times"
author: "Byeong-Hak Choe"
---

## Load Libraries

```{python}
import pandas as pd
import numpy as np
import seaborn as sns
```

<br>

# Question 1


Consider the following example DataFrames.
```{python}
banks = pd.read_csv('https://bcdanl.github.io/data/bank_failures.csv', parse_dates=["Closing Date"])

```

<br>

## Q1a
Add the new variables, `closing_quarter` and `closing_year`, to the DataFrame `banks`.
  - `closing_quarter`:  the quarter in which the bank closed (`1`, `2`, `3`, or `4`)
  - `closing_year`:  the year in which the bank closed


<br>


## Q1b
Count the number of banks that were closed for each pair of year-quarter.

<br>


## Q1c
Provide both seaborn code and a simple comment to describe the quarterly trend of bank failure.

```{python}

```




<br><br><br>

# Question 2

Consider the following stock data:

```{python}
path = 'https://bcdanl.github.io/data/stocks2013_2023.csv'
stock = pd.read_csv(path)
```

<br>

## Q2a

Add a variable, `date_dt`, which is a `datetime` type of `Date` variable, to the `stock` DataFrame.


<br>

## Q2b

- For each year, find the two dates for which 
  - `TSLA`'s `Close` was the highest of the year.
  - `TSLA`'s `Close` was the lowest of the year.
  
- Calculate the gap between the dates.




<br>

## Q2c

Find the airline that has the largest proportion of flights with longer than 30-minute `dep_delay`.



