---
title: "Causal Machine Learning Bookmarks"
format: 
  html:
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: false
    code-tools: false
    code-link: false

comments: false
---

## Causal Machine Learning

- [Dive into Causal Machine Learning](https://d2cml-ai.github.io/d2cml.ai/){target="_blank"}, The World Bank and Pontificia Universidad Católica del Perú, Alexander Quispe et. al.
<br>

- [MIT 14.388: Inference on Causal and Structural Parameters Using ML and AI](https://d2cml-ai.github.io/14.388_r/intro.html){target="_blank"}, Department of Economics, MIT, Victor Chernozukhov
  - [Python Website](https://d2cml-ai.github.io/14.388_py/intro.html){target="_blank"}
  - [Julia Website](https://d2cml-ai.github.io/14.388_jl/intro.html){target="_blank"}
<br>

- [MGTECON 634: ML-based Causal Inference](https://d2cml-ai.github.io/mgtecon634_py/md/intro.html){target="_blank"}, Stanford, Susan Athey
<br>

- [Machine Learning & Causal Inference: A Short Course](https://www.gsb.stanford.edu/faculty-research/centers-initiatives/sil/research/methods/ai-machine-learning/short-course){target="_blank"}, Stanford, Susan Athey, Jan Spiess, and Stefan Wager
  - [Tutorial](https://gsbdbi.github.io/ml_tutorial/)
  - [YouTube](https://www.youtube.com/playlist?list=PLxq_lXOUlvQAoWZEqhRqHNezS30lI49G-){target="_blank"}
<br>


- [2018 American Economic Association Continuing Education: Machine Learning and Econometrics](https://www.aeaweb.org/conference/cont-ed/2018-webcasts){target="_blank"}, Susan Athey and Guido Imbens
<br>



- [Causal Inference and Machine Learning in Practice with EconML and CausalML: Industrial Use Cases at Microsoft, TripAdvisor, Uber](https://causal-machine-learning.github.io/kdd2021-tutorial/){target="_blank"}
<br>

- [DoubleML: Python and R Packages for the Double/Debiased Machine Learning Framework](https://docs.doubleml.org){target="_blank"}, P. Bach, V. Chernozhukov, M. S. Kurz, and M. Spindler
<br>

- [EconML: A Python Package for ML-based Heterogeneous Treatment Effects Estimation](https://github.com/Microsoft/EconML){target="_blank"}, Microsoft
<br>

- [CausalML: A Python Package for ML-based Causal Inference](https://github.com/uber/causalml){target="_blank"}, Uber



<br>

## Machine Learning and Big Data


- [2023 American Economic Association Continuing Education: Machine Learning and Big Data](https://www.aeaweb.org/conference/cont-ed/2023-webcasts){target="_blank"}, Melissa Dell and Matthew Harding
<br>

- [Machine Learning for Economists (ml4econ)](https://ml4econ.github.io/course-spring2019/index.html){target="_blank"}, Bank of Israel, Itamar Caspi and Ariel Mansura
<br>


<br>

## Causal Inference

- [Causal Inference: The Mixtape](https://mixtape.scunning.com){target="_blank"}, Scott Cunningham
<br>

- [Causal Inference for the Brave and True](https://matheusfacure.github.io/python-causality-handbook/landing-page.html){target="_blank"}, Matheus Facure
<br>

- [Causal Inference and Its Applications in Online Industry](https://alexdeng.github.io/causal/){target="_blank"}, Alex Deng
<br>

- [Applied Empirical Methods](https://github.com/paulgp/applied-methods-phd){target="_blank"}, Yale SOM, Paul Goldsmith-Pinkham
  - [YouTube](https://www.youtube.com/playlist?list=PLWWcL1M3lLlojLTSVf2gGYQ_9TlPyPbiJ){target="_blank"}
<br>

- [Causal Inference with Panel Data](https://yiqingxu.org/teaching/){target="_blank"}, Department of Political Science, Stanford, Yiqing Xu
  - [YouTube](https://www.youtube.com/playlist?list=PLo0lw6BstMGZQqx_r1GnOETkFYihCgve9){target="_blank"}
<br>

- [Causal Inference: What If](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/){target="_blank"}, Miguel A. Hernán and James M. Robins
<br>

- [Recent Developments in Difference-in-Differences](https://asjadnaqvi.github.io/DiD/){target="_blank"}, Vienna University of Economics and Business, Asjad Naqvi
<br>

- [Difference-in-Differences Blog](https://diff.healthpolicydatascience.org){target="_blank"}
<br>


- [Gov 2003: Causal Inference](https://mattblackwell.github.io/gov2003-f21-site/){target="_blank"}, Department of Government, Harvard, Matthew Blackwell


<br>

## Researchers in Causal Machine Learning

- [Susan Athey](https://www.gsb.stanford.edu/faculty-research/faculty/susan-athey){target="_blank"}
<br>

- [Alexandre Belloni](https://people.duke.edu/~abn5/belloni-index.html){target="_blank"}
<br>

- [Victor Chernozhukov](https://www.mit.edu/~vchern/){target="_blank"}
<br>

- [Carlos Cinelli](https://carloscinelli.com){target="_blank"}
<br>

- [Christian Hansen](https://voices.uchicago.edu/christianhansen/){target="_blank"}
<br>

- [Guido Imbens](https://www.gsb.stanford.edu/faculty-research/faculty/guido-w-imbens){
target="_blank"}<br>

- [Jann Spiess](https://scholar.harvard.edu/spiess){target="_blank"}
<br>
- [Stefan Wager](https://web.stanford.edu/~swager/index.html)


