---
title: "GitHub Repository and Large Files"
---

- Individual files in a GitHub repository are strictly limited to a 100 MB maximum size limit.


- If we push a large file (> 100 MB) to your GitHub repository, we get the following error:
  - `remote: error File: FILE_NAME is ... this exceeds GitHub's file size limit of 100 MB.`


- Even after we remove the large file from the local repository folder, we still get the same error.


- To solve the issue, we need to follow the procedure in the following page:
  - [https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#removing-a-file-that-contained-a-password](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#removing-a-file-that-contained-a-password)
  - I recommend using the BFG to fix this problem.
  
  
- Using the BFG  
  1. Download the `bfg-1.14.0.jar` file.
    - [https://rtyley.github.io/bfg-repo-cleaner/](https://rtyley.github.io/bfg-repo-cleaner/)
  2. Move the file, `bfg-1.14.0.jar`, to your local GitHub repository folder.
  3. In Terminal where the directory is your local repo, run the following command:
    - `java -jar bfg-1.14.0.jar --delete-files YOUR-FILE-WITH-LARGE-DATA`
    - You may get the error message: `'java' is not recognized as an internal or external command, operable program or batch file.` 


- If you, a Windows user, encounter the above error message from running the above line , here is what you can do.
  
    1. Search for "Environment Variables" in the Windows search bar and click on "Edit the system environment variables".
    2. In the System Properties window that opens, click on the "Environment Variables" button.
    3. In the "Environment Variables" window, under "System Variables", scroll down and find the "Path" variable, then click on the "Edit" button.
    4. In the "Edit environment variable" window, click on the "New" button and add the path to the bin directory of your Java installation. For example, if your Java installation is in `C:\Program Files\Java\jdk1.8.0_291`, then add `C:\Program Files\Java\jdk1.8.0_291\bin` to the PATH variable.
      - Downlaod the `jdk` installation file from Oracle if it is not installed on a computer.
    5. Click "OK" in all the windows to close them.
    6. Open a new Command Prompt window and try running the BFG Repo Cleaner command again.
    



