rmarkdown::render_site("index.Rmd")
rmarkdown::render_site("resume.Rmd")
rmarkdown::render_site("DANL100_hw1q.Rmd")
rmarkdown::render_site("DANL200_hw1q.Rmd")
rmarkdown::render_site("DANL100_hw1a.Rmd")
rmarkdown::render_site("DANL200_hw1a.Rmd")
